"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Download, HandCoins, Link2, Plus, RefreshCw, RotateCcw, Search } from "lucide-react";

type Tab = "overview" | "partners" | "orders" | "settlements" | "operations" | "reports";
type DecimalLike = string | number;
type Metrics = {
  orderAmount: DecimalLike; received: DecimalLike; clientRemaining: DecimalLike; companyAmount: DecimalLike;
  partnerPlanned: DecimalLike; partnerAccrued: DecimalLike; companyPaidPartner: DecimalLike; partnerBalance: DecimalLike;
  companyDebt: DecimalLike; partnerDebt: DecimalLike; companyClientReceived: DecimalLike; clientPaidToPartner: DecimalLike;
  partnerTransferred: DecimalLike;
};
type Partner = {
  id: number; name: string; kind: string; phone?: string | null; secondaryPhone?: string | null; email?: string | null;
  city?: string | null; address?: string | null; contactPerson?: string | null; businessStatus: string; comment?: string | null;
  defaultRewardRule: string; defaultRewardPercent?: DecimalLike | null; defaultRewardFixedAmount?: DecimalLike | null;
  cooperationStartedAt?: string | null; createdAt: string; updatedAt: string;
  totals: { orders: number; orderAmount: DecimalLike; received: DecimalLike; clientRemaining: DecimalLike; partnerAccrued: DecimalLike; partnerPaid: DecimalLike; balance: DecimalLike; profit: DecimalLike };
};
type PartnerOrder = {
  id: number; partnerId: number; settlementStatus: string; rewardRule: string; rewardPercent?: DecimalLike | null; fixedAmount?: DecimalLike | null;
  partner: Partner; metrics: Metrics; operations: Operation[];
  order: { id: number; number: string; createdAt: string; orderReceivedAt: string; lifecycle: string; client: { id: number; name: string; phone: string; city: string }; manager: { id: number | null; name: string }; address: string; staircase: string; material: string; amount: DecimalLike; companyProfit: DecimalLike; status: string; contract?: { number?: string | null } | null };
  economy: {
    client: { totalSale: DecimalLike; netReceived: DecimalLike; remaining: DecimalLike };
    partner: { agreed: DecimalLike; accrued: DecimalLike; paid: DecimalLike; remaining: DecimalLike };
    profit: { marginBeforePayroll: DecimalLike; payrollAccrued: DecimalLike; netProfit: DecimalLike; netMarginPercent: DecimalLike };
  };
};
type Operation = { id: number; relationId: number; type: string; status: string; amount: DecimalLike; operationDate: string; method?: string | null; account?: string | null; comment?: string | null; orderNumber?: string; partnerName?: string; createdBy?: { name: string } };
type Payload = {
  partners: Partner[]; orders: PartnerOrder[]; operations: Operation[]; audits: Array<{ id: number; action: string; createdAt: string; comment?: string | null; actor?: { name: string } }>;
  managers: Array<{ id: number; name: string }>;
  totals: { activePartners: number; orders: number; orderAmount: DecimalLike; received: DecimalLike; clientRemaining: DecimalLike; companyAmount: DecimalLike; partnerAccrued: DecimalLike; partnerPaid: DecimalLike; companyDebt: DecimalLike; partnerDebt: DecimalLike; averageOrder: DecimalLike; profit: DecimalLike };
  charts: { monthly: Array<{ month: string; orders: number; sales: DecimalLike; received: DecimalLike }>; partners: Array<{ partnerId: number; name: string; orders: number; sales: DecimalLike; profit: DecimalLike; debt: DecimalLike }> };
};
type SearchOrder = { id: number; number: string; amount: DecimalLike; status: string; address: string; staircase: string; material: string; client: { name: string; phone: string }; documents: Array<{ number: string }>; partnerRelation?: { id: number; partner: { name: string } } | null };
type SearchClient = { id: number; name: string; phone: string; whatsapp?: string | null; city?: string | null; address?: string | null };

const tabs: Array<[Tab, string]> = [["overview", "Обзор"], ["partners", "Партнёры"], ["orders", "Заказы партнёров"], ["settlements", "Взаиморасчёты"], ["operations", "Выплаты"], ["reports", "Отчёты"]];
const money = (value: DecimalLike | null | undefined) => `${Math.round(Number(value) || 0).toLocaleString("ru-RU")} ₸`;
const date = (value: string) => new Intl.DateTimeFormat("ru-RU").format(new Date(value));
const field = "min-h-11 w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-white outline-none focus:border-amber-300";
const primary = "inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-amber-300 px-4 py-2 text-sm font-bold text-slate-950 transition hover:bg-amber-200 disabled:opacity-50";
const secondary = "inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-slate-700 bg-slate-900 px-4 py-2 text-sm font-semibold text-white transition hover:border-slate-500 disabled:opacity-50";
const panel = "rounded-2xl border border-white/10 bg-[#0b1220] p-4 sm:p-5";

export default function PartnerManagementWorkspace() {
  const [tab, setTab] = useState<Tab>("overview");
  const [data, setData] = useState<Payload | null>(null);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [query, setQuery] = useState("");

  const load = useCallback(async () => {
    setLoading(true); setError("");
    try {
      const response = await fetch(`/api/partner-management${query ? `?q=${encodeURIComponent(query)}` : ""}`, { cache: "no-store" });
      const payload = await response.json() as Payload & { error?: string };
      if (!response.ok) throw new Error(payload.error ?? "Не удалось загрузить партнёров");
      setData(payload);
    } catch (reason) { setError(reason instanceof Error ? reason.message : "Не удалось загрузить партнёров"); }
    finally { setLoading(false); }
  }, [query]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);

  const mutate = async (body: Record<string, unknown>, idempotent = false) => {
    setBusy(true); setError(""); setNotice("");
    try {
      const response = await fetch("/api/partner-management", {
        method: "POST", headers: { "content-type": "application/json", ...(idempotent ? { "Idempotency-Key": crypto.randomUUID() } : {}) }, body: JSON.stringify(body),
      });
      const payload = await response.json() as { error?: string };
      if (!response.ok) throw new Error(payload.error ?? "Операция не выполнена");
      setNotice("Сохранено"); await load(); return true;
    } catch (reason) { setError(reason instanceof Error ? reason.message : "Операция не выполнена"); return false; }
    finally { setBusy(false); }
  };

  return <main className="min-w-0 space-y-5 overflow-x-hidden p-4 text-slate-100 sm:p-6 md:p-8">
    <header className="relative overflow-hidden rounded-[28px] border border-amber-300/20 bg-[#0b1220] p-5 sm:p-7">
      <div className="absolute inset-x-0 top-0 h-px bg-amber-300/70"/>
      <div className="relative flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
        <div><p className="text-xs font-bold uppercase tracking-[0.25em] text-amber-300">Director workspace</p><h1 className="mt-2 text-3xl font-semibold text-white">Партнёры</h1><p className="mt-2 text-sm text-slate-400">Заказы, вознаграждения и взаиморасчёты в одном месте</p></div>
        <button type="button" onClick={() => void load()} disabled={loading} className={secondary}><RefreshCw size={17} className={loading ? "animate-spin" : ""}/>Обновить</button>
      </div>
    </header>
    <nav aria-label="Разделы партнёров" className="flex max-w-full gap-2 overflow-x-auto pb-1">{tabs.map(([value, label]) => <button key={value} type="button" onClick={() => setTab(value)} className={`min-h-11 shrink-0 rounded-xl px-4 text-sm font-semibold ${tab === value ? "bg-amber-300 text-slate-950" : "border border-slate-800 bg-slate-900 text-slate-300"}`}>{label}</button>)}</nav>
    {error && <div role="alert" className="rounded-xl border border-red-500/40 bg-red-950/40 p-4 text-red-200">{error}</div>}
    {notice && <div role="status" className="rounded-xl border border-emerald-500/30 bg-emerald-950/30 p-4 text-emerald-200">{notice}</div>}
    {loading && !data ? <div className={`${panel} py-16 text-center text-slate-400`}>Загрузка…</div> : data && <>
      {tab === "overview" && <Overview data={data}/>}
      {tab === "partners" && <Partners data={data} busy={busy} mutate={mutate}/>}
      {tab === "orders" && <Orders data={data} busy={busy} mutate={mutate} query={query} setQuery={setQuery}/>}
      {tab === "settlements" && <Settlements orders={data.orders} busy={busy} mutate={mutate}/>}
      {tab === "operations" && <Operations data={data} busy={busy} mutate={mutate}/>}
      {tab === "reports" && <Reports data={data}/>}
    </>}
  </main>;
}

function Overview({ data }: { data: Payload }) {
  const cards: Array<[string, DecimalLike, "money" | "count"]> = [
    ["Активные партнёры", data.totals.activePartners, "count"], ["Заказы партнёров", data.totals.orders, "count"],
    ["Сумма заказов", data.totals.orderAmount, "money"], ["Получено от клиентов", data.totals.received, "money"],
    ["Остаток клиентов", data.totals.clientRemaining, "money"], ["Сумма компании", data.totals.companyAmount, "money"],
    ["Начислено партнёрам", data.totals.partnerAccrued, "money"], ["Выплачено партнёрам", data.totals.partnerPaid, "money"],
    ["Компания должна", data.totals.companyDebt, "money"], ["Партнёры должны", data.totals.partnerDebt, "money"],
    ["Средний заказ", data.totals.averageOrder, "money"], ["Прибыль", data.totals.profit, "money"],
  ];
  const max = Math.max(1, ...data.charts.partners.map((item) => Number(item.sales)));
  return <div className="space-y-5"><section className="grid grid-cols-2 gap-3 lg:grid-cols-4">{cards.map(([label, value, kind]) => <div key={label} className={panel}><p className="text-xs text-slate-400 sm:text-sm">{label}</p><p className="mt-2 break-words text-lg font-bold text-white sm:text-2xl">{kind === "money" ? money(value) : value}</p></div>)}</section>
    <section className="grid gap-5 xl:grid-cols-2"><div className={panel}><h2 className="text-lg font-bold">Продажи по партнёрам</h2><div className="mt-5 space-y-4">{data.charts.partners.slice(0, 8).map((item) => <div key={item.partnerId}><div className="flex justify-between gap-3 text-sm"><span className="truncate">{item.name}</span><span>{money(item.sales)}</span></div><div className="mt-1 h-2 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-amber-300" style={{ width: `${Math.max(2, Number(item.sales) / max * 100)}%` }}/></div></div>)}{!data.charts.partners.length && <Empty/>}</div></div>
      <div className={panel}><h2 className="text-lg font-bold">Продажи по месяцам</h2><div className="mt-5 space-y-3">{data.charts.monthly.slice(-8).map((item) => <div key={item.month} className="grid grid-cols-[5rem_1fr] gap-3 rounded-xl bg-slate-900 p-3 text-sm"><span>{item.month}</span><span className="text-right">{item.orders} заказов · {money(item.sales)} · получено {money(item.received)}</span></div>)}{!data.charts.monthly.length && <Empty/>}</div></div></section>
  </div>;
}

function Partners({ data, busy, mutate }: { data: Payload; busy: boolean; mutate: (body: Record<string, unknown>, idem?: boolean) => Promise<boolean> }) {
  const [open, setOpen] = useState(false); const [selected, setSelected] = useState<number | null>(null);
  const [form, setForm] = useState({ name: "", kind: "REFERRER", phone: "", secondaryPhone: "", email: "", city: "", address: "", contactPerson: "", cooperationStartedAt: "", rewardRule: "ORDER_PERCENT", rewardPercent: "10", fixedAmount: "", comment: "" });
  const submit = async (event: FormEvent) => { event.preventDefault(); if (await mutate({ action: "create-partner", ...form })) { setOpen(false); setForm({ ...form, name: "", phone: "", secondaryPhone: "", email: "", comment: "" }); } };
  const partner = data.partners.find((item) => item.id === selected);
  return <div className="space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:justify-between"><div><h2 className="text-xl font-bold">Справочник партнёров</h2><p className="text-sm text-slate-400">Архивирование сохраняет всю историю.</p></div><button type="button" onClick={() => setOpen((value) => !value)} className={primary}><Plus size={17}/>Добавить партнёра</button></div>
    {open && <form onSubmit={submit} className={`${panel} grid gap-3 md:grid-cols-2 xl:grid-cols-3`}><FormTitle>Новый партнёр</FormTitle><Input label="Название / ФИО" value={form.name} required onChange={(value) => setForm({ ...form, name: value })}/><Select label="Тип" value={form.kind} onChange={(value) => setForm({ ...form, kind: value })} options={partnerKinds}/><Input label="Телефон" value={form.phone} onChange={(value) => setForm({ ...form, phone: value })}/><Input label="Дополнительный телефон" value={form.secondaryPhone} onChange={(value) => setForm({ ...form, secondaryPhone: value })}/><Input label="Email" type="email" value={form.email} onChange={(value) => setForm({ ...form, email: value })}/><Input label="Город" value={form.city} onChange={(value) => setForm({ ...form, city: value })}/><Input label="Адрес" value={form.address} onChange={(value) => setForm({ ...form, address: value })}/><Input label="Ответственное лицо" value={form.contactPerson} onChange={(value) => setForm({ ...form, contactPerson: value })}/><Input label="Дата начала" type="date" value={form.cooperationStartedAt} onChange={(value) => setForm({ ...form, cooperationStartedAt: value })}/><Select label="Вознаграждение" value={form.rewardRule} onChange={(value) => setForm({ ...form, rewardRule: value })} options={rewardRules}/>{form.rewardRule.includes("PERCENT") && <Input label="Процент" type="number" value={form.rewardPercent} onChange={(value) => setForm({ ...form, rewardPercent: value })}/>} {form.rewardRule === "FIXED" && <Input label="Фиксированная сумма" type="number" value={form.fixedAmount} onChange={(value) => setForm({ ...form, fixedAmount: value })}/>}<Input label="Комментарий" value={form.comment} onChange={(value) => setForm({ ...form, comment: value })}/><div className="flex items-end"><button disabled={busy} className={`${primary} w-full`}>Сохранить</button></div></form>}
    <div className="grid gap-4 xl:grid-cols-2">{data.partners.map((item) => <article key={item.id} className={panel}><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-lg font-bold text-white">{item.name}</h3><p className="mt-1 text-sm text-slate-400">{kindLabel(item.kind)} · {item.city || "город не указан"}</p></div><Status value={item.businessStatus}/></div><div className="mt-4 grid grid-cols-2 gap-2 text-sm"><Mini label="Заказов" value={String(item.totals.orders)}/><Mini label="Сумма" value={money(item.totals.orderAmount)}/><Mini label="Начислено" value={money(item.totals.partnerAccrued)}/><Mini label="Баланс" value={money(item.totals.balance)}/></div><div className="mt-4 flex flex-wrap gap-2"><button type="button" className={secondary} onClick={() => setSelected(selected === item.id ? null : item.id)}>Карточка</button><button type="button" className={secondary} disabled={busy} onClick={() => void mutate({ action: "update-partner", partnerId: item.id, businessStatus: item.businessStatus === "ARCHIVED" ? "ACTIVE" : "ARCHIVED" })}>{item.businessStatus === "ARCHIVED" ? "Активировать" : "В архив"}</button></div>{selected === item.id && partner && <PartnerDetails partner={partner} orders={data.orders.filter((order) => order.partnerId === partner.id)} audits={data.audits}/>}</article>)}{!data.partners.length && <Empty/>}</div>
  </div>;
}

function PartnerDetails({ partner, orders, audits }: { partner: Partner; orders: PartnerOrder[]; audits: Payload["audits"] }) {
  return <div className="mt-5 space-y-4 border-t border-white/10 pt-5 text-sm"><div className="grid gap-2 sm:grid-cols-2"><p>Телефон: <b>{partner.phone || "—"}</b></p><p>Email: <b>{partner.email || "—"}</b></p><p>Контакт: <b>{partner.contactPerson || "—"}</b></p><p>Начало работы: <b>{partner.cooperationStartedAt ? date(partner.cooperationStartedAt) : "—"}</b></p></div><p className="text-slate-300">{partner.comment || "Комментарий не указан"}</p><h4 className="font-bold">Заказы</h4>{orders.slice(0, 5).map((item) => <p key={item.id}>{item.order.number} · {item.order.client.name} · {money(item.metrics.orderAmount)}</p>)}<h4 className="font-bold">История</h4>{audits.slice(0, 5).map((item) => <p key={item.id} className="text-slate-400">{date(item.createdAt)} · {item.action} · {item.actor?.name ?? "Система"}</p>)}</div>;
}

function Orders({ data, busy, mutate, query, setQuery }: { data: Payload; busy: boolean; mutate: (body: Record<string, unknown>, idem?: boolean) => Promise<boolean>; query: string; setQuery: (value: string) => void }) {
  const [mode, setMode] = useState<"link" | "create" | null>(null); const [search, setSearch] = useState(""); const [results, setResults] = useState<SearchOrder[]>([]); const [clients, setClients] = useState<SearchClient[]>([]);
  const [link, setLink] = useState({ partnerId: "", orderId: "", rewardRule: "", rewardPercent: "", fixedAmount: "", comment: "" });
  const [order, setOrder] = useState({ partnerId: "", clientId: "", newClient: false, clientName: "", clientPhone: "", secondaryPhone: "", city: "", clientComment: "", address: "", staircase: "Лестница", material: "", description: "", amount: "", orderDate: new Date().toISOString().slice(0, 10), promisedAt: "", managerUserId: "", externalContractNumber: "", status: "Новый", rewardRule: "", rewardPercent: "", fixedAmount: "", comment: "", initialConfirmed: false, initialAmount: "", initialDate: new Date().toISOString().slice(0, 10), initialReceivedBy: "", initialAccount: "", initialMethod: "bank", initialComment: "" });
  const findOrders = async () => { const response = await fetch(`/api/partner-management?view=search-orders&q=${encodeURIComponent(search)}`); if (response.ok) setResults(await response.json() as SearchOrder[]); };
  const findClients = async () => { const response = await fetch(`/api/partner-management?view=search-clients&q=${encodeURIComponent(search)}`); if (response.ok) setClients(await response.json() as SearchClient[]); };
  const linkSubmit = async (event: FormEvent) => { event.preventDefault(); if (await mutate({ action: "link-order", ...link, partnerId: Number(link.partnerId), orderId: Number(link.orderId), rewardRule: link.rewardRule || undefined })) setMode(null); };
  const createSubmit = async (event: FormEvent) => { event.preventDefault(); const body: Record<string, unknown> = { action: "create-order", ...order, partnerId: Number(order.partnerId), clientId: order.newClient ? undefined : Number(order.clientId), managerUserId: order.managerUserId ? Number(order.managerUserId) : undefined, rewardRule: order.rewardRule || undefined, client: order.newClient ? { name: order.clientName, phone: order.clientPhone, secondaryPhone: order.secondaryPhone, city: order.city, address: order.address, comment: order.clientComment } : undefined, initialPayment: order.initialConfirmed ? { confirmed: true, amount: order.initialAmount, date: order.initialDate, receivedBy: order.initialReceivedBy, account: order.initialAccount, method: order.initialMethod, comment: order.initialComment } : undefined }; if (await mutate(body, true)) setMode(null); };
  return <div className="space-y-5"><div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><label className="w-full max-w-xl text-sm text-slate-400">Поиск по партнёру, заказу, клиенту или телефону<div className="mt-1 flex gap-2"><input className={field} value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Введите запрос"/><button type="button" className={secondary}><Search size={17}/></button></div></label><div className="flex flex-col gap-2 sm:flex-row"><button type="button" onClick={() => setMode("link")} className={secondary}><Link2 size={17}/>Привязать существующий</button><button type="button" onClick={() => setMode("create")} className={primary}><Plus size={17}/>Новый заказ партнёра</button></div></div>
    {mode === "link" && <form onSubmit={linkSubmit} className={`${panel} grid gap-3 md:grid-cols-2`}><FormTitle>Привязать существующий заказ</FormTitle><Select label="Партнёр" value={link.partnerId} onChange={(value) => setLink({ ...link, partnerId: value })} options={data.partners.filter((item) => item.businessStatus !== "ARCHIVED").map((item) => [String(item.id), item.name])}/><div><span className="text-sm text-slate-400">Поиск заказа</span><div className="mt-1 flex gap-2"><input className={field} value={search} onChange={(event) => setSearch(event.target.value)}/><button type="button" className={secondary} onClick={() => void findOrders()}><Search size={16}/></button></div></div><Select label="Заказ" value={link.orderId} onChange={(value) => setLink({ ...link, orderId: value })} options={results.map((item) => [String(item.id), `${item.number} · ${item.client.name} · ${money(item.amount)}${item.partnerRelation ? ` · связан с ${item.partnerRelation.partner.name}` : ""}`])}/><Select label="Правило (или настройка партнёра)" value={link.rewardRule} onChange={(value) => setLink({ ...link, rewardRule: value })} options={[["", "По умолчанию"], ...rewardRules]}/><Input label="Процент" type="number" value={link.rewardPercent} onChange={(value) => setLink({ ...link, rewardPercent: value })}/><Input label="Фиксированная сумма" type="number" value={link.fixedAmount} onChange={(value) => setLink({ ...link, fixedAmount: value })}/><Input label="Комментарий" value={link.comment} onChange={(value) => setLink({ ...link, comment: value })}/><div className="flex items-end gap-2"><button disabled={busy} className={primary}>Привязать</button><button type="button" onClick={() => setMode(null)} className={secondary}>Отмена</button></div></form>}
    {mode === "create" && <form onSubmit={createSubmit} className={`${panel} grid gap-3 md:grid-cols-2 xl:grid-cols-3`}>
      <FormTitle>Новый обычный заказ ORDA</FormTitle>
      <Select label="Партнёр" value={order.partnerId} onChange={(value) => setOrder({ ...order, partnerId: value })} options={data.partners.filter((item) => item.businessStatus === "ACTIVE").map((item) => [String(item.id), item.name])}/>
      <label className="flex min-h-11 items-center gap-2 self-end rounded-xl border border-slate-700 px-3"><input type="checkbox" checked={order.newClient} onChange={(event) => setOrder({ ...order, newClient: event.target.checked })}/>Создать нового клиента</label>
      {!order.newClient && <><div><span className="text-sm text-slate-400">Поиск клиента</span><div className="mt-1 flex gap-2"><input className={field} value={search} onChange={(event) => setSearch(event.target.value)}/><button type="button" className={secondary} onClick={() => void findClients()}><Search size={16}/></button></div></div><Select label="Клиент" value={order.clientId} onChange={(value) => setOrder({ ...order, clientId: value })} options={clients.map((item) => [String(item.id), `${item.name} · ${item.phone}`])}/></>}
      {order.newClient && <><Input label="ФИО / компания" value={order.clientName} onChange={(value) => setOrder({ ...order, clientName: value })}/><Input label="Телефон" value={order.clientPhone} onChange={(value) => setOrder({ ...order, clientPhone: value })}/><Input label="Дополнительный телефон" value={order.secondaryPhone} onChange={(value) => setOrder({ ...order, secondaryPhone: value })}/><Input label="Город" value={order.city} onChange={(value) => setOrder({ ...order, city: value })}/><Input label="Комментарий к клиенту" value={order.clientComment} onChange={(value) => setOrder({ ...order, clientComment: value })}/></>}
      <Input label="Адрес объекта" value={order.address} onChange={(value) => setOrder({ ...order, address: value })}/><Input label="Изделие" value={order.staircase} onChange={(value) => setOrder({ ...order, staircase: value })}/><Input label="Материал" value={order.material} onChange={(value) => setOrder({ ...order, material: value })}/><Input label="Описание" value={order.description} onChange={(value) => setOrder({ ...order, description: value })}/><Input label="Сумма заказа" type="number" value={order.amount} onChange={(value) => setOrder({ ...order, amount: value })}/><Input label="Дата заказа" type="date" value={order.orderDate} onChange={(value) => setOrder({ ...order, orderDate: value })}/><Input label="Плановая готовность" type="date" value={order.promisedAt} onChange={(value) => setOrder({ ...order, promisedAt: value })}/><Input label="Внешний договор" value={order.externalContractNumber} onChange={(value) => setOrder({ ...order, externalContractNumber: value })}/><Input label="Статус" value={order.status} onChange={(value) => setOrder({ ...order, status: value })}/>
      <Select label="Менеджер (необязательно)" value={order.managerUserId} onChange={(value) => setOrder({ ...order, managerUserId: value })} options={[["", "Не назначен"], ...data.managers.map((item) => [String(item.id), item.name] as [string, string])]}/><Select label="Правило вознаграждения" value={order.rewardRule} onChange={(value) => setOrder({ ...order, rewardRule: value })} options={[["", "По умолчанию"], ...rewardRules]}/><Input label="Процент" type="number" value={order.rewardPercent} onChange={(value) => setOrder({ ...order, rewardPercent: value })}/><Input label="Фиксированная сумма" type="number" value={order.fixedAmount} onChange={(value) => setOrder({ ...order, fixedAmount: value })}/><Input label="Комментарий" value={order.comment} onChange={(value) => setOrder({ ...order, comment: value })}/>
      <label className="flex min-h-11 items-center gap-2 self-end rounded-xl border border-slate-700 px-3"><input type="checkbox" checked={order.initialConfirmed} onChange={(event) => setOrder({ ...order, initialConfirmed: event.target.checked })}/>Фактическая первоначальная оплата подтверждена</label>
      {order.initialConfirmed && <><Input label="Сумма оплаты" type="number" value={order.initialAmount} onChange={(value) => setOrder({ ...order, initialAmount: value })}/><Input label="Дата оплаты" type="date" value={order.initialDate} onChange={(value) => setOrder({ ...order, initialDate: value })}/><Input label="Кто получил" value={order.initialReceivedBy} onChange={(value) => setOrder({ ...order, initialReceivedBy: value })}/><Input label="Касса / банковский счёт" value={order.initialAccount} onChange={(value) => setOrder({ ...order, initialAccount: value })}/><Input label="Способ оплаты" value={order.initialMethod} onChange={(value) => setOrder({ ...order, initialMethod: value })}/><Input label="Комментарий к оплате" value={order.initialComment} onChange={(value) => setOrder({ ...order, initialComment: value })}/></>}
      <div className="flex items-end gap-2"><button disabled={busy} className={primary}>Создать заказ</button><button type="button" onClick={() => setMode(null)} className={secondary}>Отмена</button></div>
    </form>}
    <OrderCards orders={data.orders} actions={(item) => <><a href={`/orders/${item.order.id}`} className={secondary}>Открыть заказ</a><button type="button" disabled={busy} className={secondary} onClick={() => { const amount = window.prompt("Согласованная стоимость партнёра"); if (!amount) return; const comment = window.prompt("Комментарий к согласованию") ?? ""; void mutate({ action: "set-agreed-cost", relationId: item.id, amount, comment }); }}>Указать согласованную стоимость</button></>}/>
  </div>;
}

function OrderCards({ orders, actions }: { orders: PartnerOrder[]; actions?: (item: PartnerOrder) => React.ReactNode }) {
  return <div className="grid gap-4">{orders.map((item) => <article key={item.id} className={panel}><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><h3 className="font-bold text-white">{item.order.number} · {item.partner.name}</h3><p className="mt-1 break-words text-sm text-slate-400">{item.order.client.name.trim() || "Клиент не указан"} · {item.order.client.phone} · {item.order.client.city || "город не указан"}</p><p className="text-sm text-slate-500">{date(item.order.orderReceivedAt)} · {item.order.address}</p></div><div className="flex flex-wrap gap-2"><Status value={item.order.lifecycle}/><Status value={item.settlementStatus}/></div></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3 xl:grid-cols-5"><Mini label="Сумма продажи" value={money(item.economy.client.totalSale)}/><Mini label="Получено от клиента" value={money(item.economy.client.netReceived)}/><Mini label="Остаток клиента" value={money(item.economy.client.remaining)}/><Mini label="Согласованная стоимость" value={money(item.economy.partner.agreed)}/><Mini label="Начислено партнёру" value={money(item.economy.partner.accrued)}/><Mini label="Выплачено партнёру" value={money(item.economy.partner.paid)}/><Mini label="Осталось партнёру" value={money(item.economy.partner.remaining)}/><Mini label="Маржа до зарплаты" value={money(item.economy.profit.marginBeforePayroll)}/><Mini label="Зарплата по заказу" value={money(item.economy.profit.payrollAccrued)}/><Mini label="Чистая прибыль" value={`${money(item.economy.profit.netProfit)} · ${Number(item.economy.profit.netMarginPercent).toLocaleString("ru-RU")}%`}/></div><details className="mt-4 rounded-xl bg-slate-950 p-3"><summary className="cursor-pointer font-semibold">Полные денежные показатели</summary><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3"><Mini label="Компания получила" value={money(item.metrics.companyClientReceived)}/><Mini label="Партнёр получил" value={money(item.metrics.clientPaidToPartner)}/><Mini label="Партнёр передал" value={money(item.metrics.partnerTransferred)}/><Mini label="Компания должна" value={money(item.metrics.companyDebt)}/><Mini label="Партнёр должен" value={money(item.metrics.partnerDebt)}/><Mini label="План партнёра" value={money(item.metrics.partnerPlanned)}/></div></details>{actions && <div className="mt-4 flex flex-wrap gap-2">{actions(item)}</div>}</article>)}{!orders.length && <Empty/>}</div>;
}

function Settlements({ orders, busy, mutate }: { orders: PartnerOrder[]; busy: boolean; mutate: (body: Record<string, unknown>, idem?: boolean) => Promise<boolean> }) {
  return <div className="space-y-4"><h2 className="text-xl font-bold">Текущие взаиморасчёты</h2><OrderCards orders={[...orders].sort((a, b) => Math.abs(Number(b.metrics.partnerBalance)) - Math.abs(Number(a.metrics.partnerBalance)))} actions={(item) => <><button type="button" disabled={busy || Number(item.metrics.partnerBalance) !== 0} className={secondary} onClick={() => void mutate({ action: "settlement-state", relationId: item.id, state: "CLOSE", comment: "Закрыто директором" })}>Закрыть взаиморасчёт</button><button type="button" disabled={busy} className={secondary} onClick={() => { const comment = window.prompt("Причина спорного статуса") ?? ""; if (comment) void mutate({ action: "settlement-state", relationId: item.id, state: "DISPUTE", comment }); }}>Отметить спорным</button></>}/></div>;
}

function Operations({ data, busy, mutate }: { data: Payload; busy: boolean; mutate: (body: Record<string, unknown>, idem?: boolean) => Promise<boolean> }) {
  const [form, setForm] = useState({ relationId: "", type: "CLIENT_TO_COMPANY", amount: "", adjustmentEffect: "", operationDate: new Date().toISOString().slice(0, 10), method: "bank", account: "", comment: "" });
  const submit = async (event: FormEvent) => { event.preventDefault(); if (await mutate({ action: "operation", ...form, relationId: Number(form.relationId) }, true)) setForm({ ...form, amount: "", adjustmentEffect: "", comment: "" }); };
  return <div className="space-y-5"><form onSubmit={submit} className={`${panel} grid gap-3 md:grid-cols-2 xl:grid-cols-3`}><FormTitle>Зафиксировать операцию</FormTitle><Select label="Заказ" value={form.relationId} onChange={(value) => setForm({ ...form, relationId: value })} options={data.orders.map((item) => [String(item.id), `${item.order.number} · ${item.partner.name} · ${item.order.client.name}`])}/><Select label="Направление" value={form.type} onChange={(value) => setForm({ ...form, type: value })} options={operationTypes}/><Input label="Сумма" type="number" value={form.amount} onChange={(value) => setForm({ ...form, amount: value })}/>{form.type === "ADJUSTMENT" && <Input label="Влияние на баланс (+/−)" type="number" value={form.adjustmentEffect} onChange={(value) => setForm({ ...form, adjustmentEffect: value })}/>}<Input label="Дата" type="date" value={form.operationDate} onChange={(value) => setForm({ ...form, operationDate: value })}/><Input label="Способ" value={form.method} onChange={(value) => setForm({ ...form, method: value })}/><Input label="Касса / счёт" value={form.account} onChange={(value) => setForm({ ...form, account: value })}/><Input label="Комментарий" value={form.comment} onChange={(value) => setForm({ ...form, comment: value })}/><div className="flex items-end"><button disabled={busy} className={`${primary} w-full`}><HandCoins size={17}/>Провести</button></div></form><section className={panel}><h2 className="text-lg font-bold">Журнал операций</h2><div className="mt-4 space-y-3">{data.operations.map((item) => <div key={item.id} className="flex flex-col gap-3 rounded-xl bg-slate-950 p-3 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><p className="font-semibold">{operationLabel(item.type)} · {money(item.amount)}</p><p className="break-words text-sm text-slate-400">{date(item.operationDate)} · {item.orderNumber} · {item.partnerName} · {item.createdBy?.name ?? "Система"}{item.comment ? ` · ${item.comment}` : ""}</p></div><div className="flex items-center gap-2"><Status value={item.status}/>{item.status === "POSTED" && item.type !== "REVERSAL" && <button type="button" disabled={busy} className={secondary} onClick={() => { const reason = window.prompt("Причина сторно"); if (reason) void mutate({ action: "reverse-operation", operationId: item.id, reason }, true); }}><RotateCcw size={16}/>Сторно</button>}</div></div>)}{!data.operations.length && <Empty/>}</div></section></div>;
}

function Reports({ data }: { data: Payload }) {
  const [partnerId, setPartnerId] = useState(data.partners[0] ? String(data.partners[0].id) : ""); const [from, setFrom] = useState(""); const [to, setTo] = useState("");
  const query = useMemo(() => new URLSearchParams({ ...(from ? { from } : {}), ...(to ? { to } : {}) }).toString(), [from, to]);
  return <div className="space-y-5"><section className={`${panel} grid gap-3 md:grid-cols-2 xl:grid-cols-4`}><FormTitle>Выписка по партнёру</FormTitle><Select label="Партнёр" value={partnerId} onChange={setPartnerId} options={data.partners.map((item) => [String(item.id), item.name])}/><Input label="С" type="date" value={from} onChange={setFrom}/><Input label="По" type="date" value={to} onChange={setTo}/><div className="flex flex-col gap-2 sm:flex-row xl:col-span-4"><a className={primary} href={`/api/partner-management/${partnerId}/statement?format=pdf&${query}`}><Download size={17}/>PDF</a><a className={secondary} href={`/api/partner-management/${partnerId}/statement?format=csv&${query}`}><Download size={17}/>CSV</a></div></section><section className={panel}><h2 className="text-lg font-bold">Аналитика партнёров</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{data.charts.partners.map((item) => <div key={item.partnerId} className="rounded-xl bg-slate-950 p-4"><p className="font-bold">{item.name}</p><p className="mt-2 text-sm text-slate-400">{item.orders} заказов · продажи {money(item.sales)} · прибыль {money(item.profit)} · баланс {money(item.debt)}</p></div>)}{!data.charts.partners.length && <Empty/>}</div></section></div>;
}

function Input({ label, value, onChange, type = "text", required = false }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean }) { return <label className="text-sm text-slate-400"><span>{label}</span><input className={`${field} mt-1`} type={type} required={required} value={value} onChange={(event) => onChange(event.target.value)}/></label>; }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: Array<readonly [string, string]> }) { return <label className="text-sm text-slate-400"><span>{label}</span><select className={`${field} mt-1`} value={value} onChange={(event) => onChange(event.target.value)}><option value="">Выберите</option>{options.map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select></label>; }
function FormTitle({ children }: { children: React.ReactNode }) { return <h2 className="text-lg font-bold text-white md:col-span-2 xl:col-span-3">{children}</h2>; }
function Mini({ label, value }: { label: string; value: string }) { return <div className="min-w-0 rounded-xl bg-slate-950 p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 break-words text-sm font-bold text-slate-100">{value}</p></div>; }
function Empty() { return <p className="rounded-xl border border-dashed border-slate-700 p-8 text-center text-sm text-slate-500">Данных пока нет</p>; }
function Status({ value }: { value: string }) { return <span className="inline-flex rounded-full border border-white/10 bg-slate-800 px-2.5 py-1 text-xs font-semibold text-slate-200">{statusLabel(value)}</span>; }

const partnerKinds: Array<[string, string]> = [["REFERRER", "Рекомендатель"], ["SALES_AGENT", "Агент по продажам"], ["DEALER", "Дилер"], ["DESIGNER", "Дизайнер"], ["ARCHITECT", "Архитектор"], ["CONSTRUCTION_COMPANY", "Строительная компания"], ["CONTRACTOR", "Подрядчик"], ["OTHER", "Другой"]];
const rewardRules: Array<[string, string]> = [["FIXED", "Фиксированная сумма"], ["ORDER_PERCENT", "% от суммы заказа"], ["PAID_PERCENT", "% от полученной оплаты"], ["PROFIT_PERCENT", "% от валовой прибыли"], ["MANUAL", "Ручная сумма"]];
const operationTypes: Array<[string, string]> = [["CLIENT_TO_COMPANY", "Клиент → компания"], ["CLIENT_TO_PARTNER", "Клиент → партнёр"], ["PARTNER_TO_COMPANY", "Партнёр → компания"], ["COMPANY_TO_PARTNER", "Компания → партнёр"], ["CLIENT_REFUND", "Возврат клиенту"], ["PARTNER_REFUND", "Возврат от партнёра"], ["ADJUSTMENT", "Корректировка"]];
const kindLabel = (value: string) => partnerKinds.find(([key]) => key === value)?.[1] ?? value;
const operationLabel = (value: string) => operationTypes.find(([key]) => key === value)?.[1] ?? (value === "REVERSAL" ? "Сторно" : value);
const statusLabel = (value: string) => ({ ACTIVE: "Активный", SUSPENDED: "Приостановлен", ARCHIVED: "Архивный", NOT_CALCULATED: "Не рассчитан", CALCULATED: "Рассчитан", PARTIALLY_PAID: "Частично выплачен", CLOSED: "Закрыт", PARTNER_OWES_COMPANY: "Партнёр должен", COMPANY_OWES_PARTNER: "Компания должна", DISPUTED: "Спорный", CANCELLED: "Отменён", POSTED: "Проведена", REVERSED: "Сторнирована" } as Record<string, string>)[value] ?? value;
