"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, Banknote, Factory, RefreshCw, ShoppingBag, UsersRound } from "lucide-react";
import { isProductionOverdue } from "@/lib/production/kanban";
import type { ProductionKanbanItem } from "@/components/production/ProductionKanban";

type Period = "today" | "week" | "month";
type Analytics = {
  sales: { newLeads: number; proposalsSent: number; measurementsScheduled: number; measurementsCompleted: number; won: number; lost: number; conversion: number };
  attention: { overdueNextActions: number; leadsWithoutNextAction: number; pendingPriceApprovals: number };
  managers: Array<{ manager: string; newLeads: number; processed: number; proposals: number; followUps: number; measurements: number; won: number; lost: number; conversion: number; overdueNextActions: number }>;
  lostReasons: Array<{ reason: string | null; count: number }>;
  sourcePerformance: Array<{ source: string | null; leads: number; won: number; conversion: number }>;
};
type Finance = { totals: { turnover: number; clientBalance: number; partnerBalance: number; profit: number }; operationTotals: { income: number } };
type Warehouse = { stats: { lowStock: number } };
const periodNames: Record<Period, string> = { today: "Сегодня", week: "Неделя", month: "Месяц" };
const money = (value: number) => `${Math.round(value).toLocaleString("ru-RU")} ₸`;
function range(period: Period) { const to = new Date(), from = new Date(to); if (period === "today") from.setHours(0, 0, 0, 0); if (period === "week") from.setDate(to.getDate() - 7); if (period === "month") from.setMonth(to.getMonth() - 1); return { from: from.toISOString(), to: to.toISOString() }; }

export default function DirectorCockpit() {
  const [period, setPeriod] = useState<Period>("month"), [analytics, setAnalytics] = useState<Analytics | null>(null), [finance, setFinance] = useState<Finance | null>(null), [production, setProduction] = useState<ProductionKanbanItem[]>([]), [warehouse, setWarehouse] = useState<Warehouse | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); const dates = range(period); try { const responses = await Promise.allSettled([fetch(`/api/dashboard/sales?period=${period}`, { cache: "no-store" }), fetch(`/api/finance?from=${encodeURIComponent(dates.from)}&to=${encodeURIComponent(dates.to)}`, { cache: "no-store" }), fetch("/api/production", { cache: "no-store" }), fetch("/api/warehouse?page=1&pageSize=1", { cache: "no-store" })]); const parse = async <T,>(index: number) => responses[index].status === "fulfilled" && responses[index].value.ok ? responses[index].value.json() as Promise<T> : null; setAnalytics(await parse<Analytics>(0)); setFinance(await parse<Finance>(1)); setProduction(await parse<ProductionKanbanItem[]>(2) ?? []); setWarehouse(await parse<Warehouse>(3)); if (responses.some((item) => item.status === "rejected" || !item.value.ok)) setError("Часть показателей недоступна. Доступные данные показаны без подстановок."); } catch { setError("Не удалось загрузить cockpit. Повторите попытку."); } finally { setLoading(false); } }, [period]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const productionKpi = useMemo(() => ({ inProgress: production.filter((item) => item.stage !== "Сдано").length, overdue: production.filter((item) => isProductionOverdue(item)).length, ready: production.filter((item) => item.stage === "Готово к монтажу").length, installation: production.filter((item) => item.stage === "Монтаж").length }), [production]);
  return <section className="space-y-6 p-4 sm:p-6 md:p-8"><header className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-sm font-semibold uppercase tracking-widest text-amber-400">DIRECTOR COCKPIT</p><h1 className="mt-1 text-2xl font-bold text-white sm:text-3xl">Состояние компании</h1><p className="mt-1 text-slate-400">Реальные показатели продаж, денег и исполнения.</p></div><div className="flex flex-col gap-3 sm:flex-row"><div role="group" aria-label="Период" className="grid grid-cols-3 rounded-xl border border-slate-700 bg-slate-900 p-1">{(Object.keys(periodNames) as Period[]).map((value) => <button key={value} aria-pressed={period === value} onClick={() => setPeriod(value)} className={`min-h-11 rounded-lg px-4 text-sm font-semibold ${period === value ? "bg-blue-600 text-white" : "text-slate-300"}`}>{periodNames[value]}</button>)}</div><button onClick={() => void load()} disabled={loading} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-slate-700 bg-slate-900 px-4 font-semibold"><RefreshCw size={18} className={loading ? "animate-spin" : ""}/>Обновить</button></div></header>
  {error && <p role="alert" className="rounded-xl border border-amber-500/40 bg-amber-500/10 p-4 text-amber-200">{error}</p>}
  <Attention analytics={analytics?.attention} productionOverdue={productionKpi.overdue} lowStock={warehouse?.stats.lowStock}/>
  <Section title="Продажи" icon={ShoppingBag} href="/analytics">{analytics ? <MetricGrid items={[["Новые заявки", analytics.sales.newLeads], ["КП отправлено", analytics.sales.proposalsSent], ["Замеры назначены", analytics.sales.measurementsScheduled], ["Замеры проведены", analytics.sales.measurementsCompleted], ["WON", analytics.sales.won], ["LOST", analytics.sales.lost], ["Конверсия", `${analytics.sales.conversion}%`]]}/> : <Unavailable text="Данные sales funnel недоступны."/>}</Section>
  <Section title="Деньги" icon={Banknote} href="/finance">{finance ? <MetricGrid items={[[`Поступления · ${periodNames[period].toLowerCase()}`, money(finance.operationTotals.income)], ["Задолженность клиентов", money(finance.totals.clientBalance)], ["Обязательства перед ЦЕХ", money(finance.totals.partnerBalance)], ["Оборот", money(finance.totals.turnover)], ["Доступная прибыль", money(finance.totals.profit)]]}/> : <Unavailable text="Финансовая сводка недоступна."/>}</Section>
  <Section title="Производство" icon={Factory} href="/production"><MetricGrid items={[["В работе", productionKpi.inProgress], ["Просрочено", productionKpi.overdue], ["Готово к монтажу", productionKpi.ready], ["Монтаж", productionKpi.installation]]}/></Section>
  <Section title="Менеджеры" icon={UsersRound} href="/analytics">{analytics?.managers.length ? <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{analytics.managers.map((manager) => <article key={manager.manager} className="rounded-xl border border-slate-700 bg-slate-900 p-4"><h3 className="font-bold text-white">{manager.manager}</h3><dl className="mt-3 grid grid-cols-2 gap-3 text-sm"><Mini label="Новые" value={manager.newLeads}/><Mini label="Обработано" value={manager.processed}/><Mini label="КП" value={manager.proposals}/><Mini label="Follow-up" value={manager.followUps}/><Mini label="Замеры" value={manager.measurements}/><Mini label="WON / LOST" value={`${manager.won} / ${manager.lost}`}/><Mini label="Конверсия" value={`${manager.conversion}%`}/><Mini label="Просрочено" value={manager.overdueNextActions}/></dl></article>)}</div> : <Unavailable text="Данных по менеджерам пока нет."/>}</Section>
  <div className="grid gap-6 lg:grid-cols-2"><Section title="Причины проигрыша" icon={AlertTriangle} href="/analytics">{analytics?.lostReasons.length ? <MetricGrid items={analytics.lostReasons.map((item) => [item.reason ?? "Не указана", item.count])}/> : <Unavailable text="Проигранных заявок за период нет."/>}</Section><Section title="Источники заявок" icon={UsersRound} href="/analytics">{analytics?.sourcePerformance.length ? <MetricGrid items={analytics.sourcePerformance.map((item) => [item.source ?? "Не указан", `${item.leads} · ${item.conversion}%`])}/> : <Unavailable text="Заявок за период нет."/>}</Section></div></section>;
}

function Attention({ analytics, productionOverdue, lowStock }: { analytics?: Analytics["attention"]; productionOverdue?: number; lowStock?: number }) { const total = (analytics?.overdueNextActions ?? 0) + (analytics?.leadsWithoutNextAction ?? 0) + (analytics?.pendingPriceApprovals ?? 0) + (productionOverdue ?? 0) + (lowStock ?? 0); return <section className={`rounded-2xl border p-5 ${total ? "border-red-500/50 bg-red-950/30" : "border-slate-700 bg-[#101827]"}`}><div className="flex items-center gap-3"><AlertTriangle className={total ? "text-red-400" : "text-slate-500"}/><div><h2 className="text-lg font-bold">Требует внимания</h2><p className="text-sm text-slate-400">Продажи, производство и склад.</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{analytics ? <><Signal href="/clients" label="Просроченные действия" value={analytics.overdueNextActions}/><Signal href="/clients" label="Без следующего действия" value={analytics.leadsWithoutNextAction}/><Signal href="/price-approvals" label="Согласования цены" value={analytics.pendingPriceApprovals}/></> : <Unavailable text="Sales attention недоступен"/>}<Signal href="/production" label="Просрочено производство" value={productionOverdue ?? 0}/><Signal href="/warehouse" label="Низкие остатки" value={lowStock ?? 0}/></div></section>; }
function Section({ title, icon: Icon, href, children }: { title: string; icon: typeof ShoppingBag; href: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-slate-700 bg-[#101827] p-4 sm:p-5"><header className="mb-4 flex items-center justify-between gap-3"><div className="flex items-center gap-3"><Icon className="text-blue-400"/><h2 className="text-xl font-bold">{title}</h2></div><Link href={href} className="min-h-11 rounded-lg px-3 py-2 text-sm font-semibold text-blue-300">Подробнее</Link></header>{children}</section>; }
function MetricGrid({ items }: { items: Array<[string, string | number]> }) { return <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{items.map(([label, value]) => <article key={label} className="rounded-xl border border-slate-700 bg-slate-900 p-4"><p className="text-sm text-slate-400">{label}</p><p className="mt-2 break-words text-2xl font-bold">{value}</p></article>)}</div>; }
function Mini({ label, value }: { label: string; value: string | number }) { return <div><dt className="text-slate-500">{label}</dt><dd className="text-lg font-bold">{value}</dd></div>; }
function Signal({ href, label, value }: { href: string; label: string; value: number }) { return <Link href={href} className="flex min-h-14 items-center justify-between rounded-xl border border-slate-700 bg-slate-900 px-4"><span className="text-sm text-slate-300">{label}</span><strong className={value ? "text-xl text-red-300" : "text-xl text-emerald-300"}>{value}</strong></Link>; }
function Unavailable({ text }: { text: string }) { return <p className="rounded-xl border border-dashed border-slate-700 p-5 text-sm text-slate-500">{text}</p>; }
