"use client";

import Link from "next/link";
import { Clock3, MessageCircle, Phone, RefreshCw } from "lucide-react";
import { useCallback, useEffect, useState } from "react";

type QueueItem = { clientId: number; name: string; phone: string; stage: string; kind: "OVERDUE" | "TODAY" | "NEW" | "PROPOSAL_WITHOUT_FOLLOW_UP" | "APPROVED_PRICE"; overdueLabel?: string | null; nextAction?: { nextActionType: string; nextActionAt: string; nextActionComment?: string | null } | null };
const groups: Array<[QueueItem["kind"], string]> = [["OVERDUE", "Просрочено"], ["TODAY", "Сегодня"], ["NEW", "Новые необработанные"], ["PROPOSAL_WITHOUT_FOLLOW_UP", "КП без follow-up"], ["APPROVED_PRICE", "Одобренные специальные цены"]];
const actionNames: Record<string, string> = { CALL: "Позвонить", WHATSAPP: "Написать WhatsApp", FOLLOW_UP: "Повторный контакт", MEASUREMENT: "Замер", MEETING: "Встреча", CALCULATION: "Подготовить расчёт", PROPOSAL: "Отправить КП", OTHER: "Другое" };

export default function ManagerToday() {
  const [items, setItems] = useState<QueueItem[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch("/api/clients/today", { cache: "no-store" }), body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Не удалось загрузить очередь"); setItems(body.items); } catch (reason) { setError(reason instanceof Error ? reason.message : "Не удалось загрузить очередь"); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  return <section className="space-y-6 p-4 sm:p-6 md:p-8"><header className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-widest text-blue-400">МОЙ РАБОЧИЙ ДЕНЬ</p><h1 className="mt-1 text-3xl font-bold">Сегодня</h1><p className="mt-1 text-slate-400">Кому нужно позвонить или написать прямо сейчас.</p></div><button onClick={() => void load()} disabled={loading} className="flex min-h-12 items-center gap-2 rounded-xl border border-slate-700 bg-slate-900 px-4"><RefreshCw size={18} className={loading ? "animate-spin" : ""}/>Обновить</button></header>{error && <p role="alert" className="rounded-xl border border-red-500/40 bg-red-950/30 p-4 text-red-200">{error}</p>}{loading && !items.length ? <div className="h-48 animate-pulse rounded-2xl bg-slate-900"/> : groups.map(([kind, title]) => { const rows = items.filter((item) => item.kind === kind); return <section key={kind} className="rounded-2xl border border-slate-700 bg-[#101827] p-4 sm:p-5"><div className="mb-4 flex items-center gap-3"><Clock3 className={kind === "OVERDUE" ? "text-red-400" : "text-blue-400"}/><h2 className="text-xl font-bold">{title}</h2><span className="rounded-full bg-slate-800 px-3 py-1 text-sm">{rows.length}</span></div>{rows.length ? <div className="grid gap-3 lg:grid-cols-2">{rows.map((item) => <article key={`${kind}-${item.clientId}`} className="rounded-xl border border-slate-700 bg-slate-900 p-4"><div className="flex items-start justify-between gap-3"><div><Link href={`/clients/${item.clientId}`} className="font-bold text-white hover:text-blue-300">{item.name}</Link><p className="mt-1 text-sm text-slate-400">{item.nextAction ? actionNames[item.nextAction.nextActionType] ?? item.nextAction.nextActionType : item.stage}</p></div>{item.overdueLabel && <span className="rounded-lg bg-red-950 px-2 py-1 text-xs text-red-300">{item.overdueLabel}</span>}</div><div className="mt-4 grid grid-cols-2 gap-2"><a href={`tel:${item.phone}`} className="flex min-h-12 items-center justify-center gap-2 rounded-xl bg-blue-600 font-semibold"><Phone size={18}/>Позвонить</a><a href={`https://wa.me/${item.phone.replace(/\D/g, "")}`} target="_blank" rel="noreferrer" className="flex min-h-12 items-center justify-center gap-2 rounded-xl bg-green-700 font-semibold"><MessageCircle size={18}/>WhatsApp</a></div></article>)}</div> : <p className="rounded-xl border border-dashed border-slate-700 p-5 text-sm text-slate-500">Задач в этой группе нет.</p>}</section>; })}</section>;
}
