import { Prisma, Role } from "@prisma/client";
import { prisma } from "@/lib/prisma";

export type CalendarEvent={id:string;sourceType:"measurement"|"production";orderId:number;title:string;stage:string;startDate:Date;endDate:Date|null;assignedUserId:number|null;assignedUserName:string|null;legacyAssignedName:string;client:string;manager:string;partner:string|null;city:string};
export type CalendarFilters={assignedUserId?:number;manager?:string;partnerId?:number;city?:string};
const productionStages=["Проектирование","Заготовка","Покраска","Монтаж","Сдано"];
async function getAssignee(tx:Prisma.TransactionClient,id:number,measurement:boolean,stage?:string){const user=await tx.user.findUnique({where:{id}});if(!user)throw new Error("USER_NOT_FOUND");const roles:Role[]=measurement?[Role.MEASURER,Role.DIRECTOR]:stage==="Монтаж"?[Role.INSTALLER,Role.DIRECTOR]:[Role.PRODUCTION,Role.DIRECTOR];if(!user.active||!roles.includes(user.role))throw new Error("INVALID_ASSIGNEE");return user;}
export async function getCalendarData(filters:CalendarFilters={}){const [measurements,productions,orders]=await Promise.all([prisma.measurement.findMany({include:{measurerUser:true,order:{include:{client:true,partner:true}}}}),prisma.production.findMany({include:{masterUser:true,order:{include:{client:true,partner:true}}}}),prisma.order.findMany({include:{client:true,partner:true}})]);const events:CalendarEvent[]=[...measurements.map(x=>({id:String(x.id),sourceType:"measurement" as const,orderId:x.orderId,title:"Замер",stage:"Замер",startDate:x.visitDate,endDate:null,assignedUserId:x.measurerUserId,assignedUserName:x.measurerUser?.name??null,legacyAssignedName:x.measurer,client:x.order.client.name,manager:x.order.manager,partner:x.order.partner?.name??null,city:x.order.client.city})),...productions.filter(x=>x.startDate||x.finishDate).map(x=>({id:String(x.id),sourceType:"production" as const,orderId:x.orderId,title:x.stage,stage:x.stage,startDate:x.startDate??x.finishDate!,endDate:x.finishDate,assignedUserId:x.masterUserId,assignedUserName:x.masterUser?.name??null,legacyAssignedName:x.master,client:x.order.client.name,manager:x.order.manager,partner:x.order.partner?.name??null,city:x.order.client.city}))];const filtered=events.filter(x=>(!filters.assignedUserId||x.assignedUserId===filters.assignedUserId)&&(!filters.manager||x.manager===filters.manager)&&(!filters.city||x.city===filters.city));return {events:filtered,orders:orders.map(x=>({id:x.id,number:x.number,client:x.client.name})),filters:{assignees:[...new Map(events.filter(x=>x.assignedUserId).map(x=>[x.assignedUserId,{id:x.assignedUserId!,name:x.assignedUserName??x.legacyAssignedName}])).values()]}};}
export async function createCalendarEvent(data:{sourceType:"measurement"|"production";orderId:number;startDate:Date;assignedUserId:number;stage?:string;comment?:string;user:string}){return prisma.$transaction(async tx=>{const order=await tx.order.findUnique({where:{id:data.orderId}});if(!order)return null;if(data.sourceType==="measurement"){const user=await getAssignee(tx,data.assignedUserId,true);const item=await tx.measurement.create({data:{orderId:order.id,measurerUserId:user.id,measurer:user.name,visitDate:data.startDate,comment:data.comment}});await tx.orderEvent.create({data:{orderId:order.id,title:"Запланирован замер",user:data.user}});return item;}if(!data.stage||!productionStages.includes(data.stage))throw new Error("INVALID_STAGE");const user=await getAssignee(tx,data.assignedUserId,false,data.stage);const item=await tx.production.create({data:{orderId:order.id,stage:data.stage,percent:0,masterUserId:user.id,master:user.name,startDate:data.startDate,comment:data.comment}});await tx.orderEvent.create({data:{orderId:order.id,title:"Запланирован этап",user:data.user}});return item;});}
export async function moveCalendarEvent(data:{sourceType:"measurement"|"production";id:number;startDate:Date;user:string}){return prisma.$transaction(async tx=>{if(data.sourceType==="measurement"){const item=await tx.measurement.update({where:{id:data.id},data:{visitDate:data.startDate}});await tx.orderEvent.create({data:{orderId:item.orderId,title:"Перенесён замер",user:data.user}});return item;}const item=await tx.production.update({where:{id:data.id},data:{startDate:data.startDate}});await tx.orderEvent.create({data:{orderId:item.orderId,title:"Перенесён этап",user:data.user}});return item;});}
