ALTER TABLE "Client" ADD COLUMN "estimatedAmount" DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE "Client" ADD COLUMN "estimateNotes" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Client" ADD COLUMN "source" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Client" ADD COLUMN "comment" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Client" ADD COLUMN "active" BOOLEAN NOT NULL DEFAULT true;
