ALTER TYPE "MeasurementPhotoType" ADD VALUE IF NOT EXISTS 'OBJECT_FRONT';
ALTER TYPE "MeasurementPhotoType" ADD VALUE IF NOT EXISTS 'OBJECT_SIDE';
ALTER TYPE "MeasurementPhotoType" ADD VALUE IF NOT EXISTS 'OBJECT_REAR';
ALTER TYPE "MeasurementPhotoType" ADD VALUE IF NOT EXISTS 'DESIGN_REFERENCE';
ALTER TYPE "MeasurementPhotoType" ADD VALUE IF NOT EXISTS 'DESIGN_RESULT';

ALTER TABLE "Measurement"
ADD COLUMN "designStyle" TEXT NOT NULL DEFAULT '',
ADD COLUMN "designNotes" TEXT NOT NULL DEFAULT '',
ADD COLUMN "designPromptCopiedAt" TIMESTAMP(3),
ADD COLUMN "designShownAt" TIMESTAMP(3);
