export const STAIR_CATALOG_REFERENCES = [
  {
    id: "baroque-led-gold-front",
    fileName: "instagram/baroque-led-gold-front.jpg",
    downloadFileName: "ALTYN-SAPA-baroque-led-gold-front.jpg",
    contentType: "image/jpeg",
    publicUrl: "/catalog/stairs/instagram/baroque-led-gold-front.jpg",
    title: "Барокко · белая лестница с золотом",
    material: "Дерево · золотые балясины · подсветка",
    note: "Реальный проект ALTYN SAPA · общий вид",
    sourceUrl: "https://www.instagram.com/altyn_sapa.company/p/DbmA_dpDckZ/",
    isReal: true,
  },
  {
    id: "baroque-led-gold-full",
    fileName: "instagram/baroque-led-gold-full.jpg",
    downloadFileName: "ALTYN-SAPA-baroque-led-gold-full.jpg",
    contentType: "image/jpeg",
    publicUrl: "/catalog/stairs/instagram/baroque-led-gold-full.jpg",
    title: "Барокко · вид на два марша",
    material: "Дерево · резные элементы · подсветка",
    note: "Реальный проект ALTYN SAPA · полный ракурс",
    sourceUrl: "https://www.instagram.com/altyn_sapa.company/p/DbmA_dpDckZ/",
    isReal: true,
  },
  {
    id: "baroque-led-gold-detail",
    fileName: "instagram/baroque-led-gold-detail.jpg",
    downloadFileName: "ALTYN-SAPA-baroque-led-gold-detail.jpg",
    contentType: "image/jpeg",
    publicUrl: "/catalog/stairs/instagram/baroque-led-gold-detail.jpg",
    title: "Барокко · детали подсветки и ограждения",
    material: "Золотые балясины · декор подступенков",
    note: "Реальный проект ALTYN SAPA · крупный план",
    sourceUrl: "https://www.instagram.com/altyn_sapa.company/p/DbmA_dpDckZ/",
    isReal: true,
  },
  {
    id: "altyn-sapa-modern-reference",
    fileName: "altyn-sapa-modern-reference.webp",
    downloadFileName: "ALTYN-SAPA-modern-design-reference.webp",
    contentType: "image/webp",
    publicUrl: "/catalog/stairs/altyn-sapa-modern-reference.webp",
    title: "Современная лестница с подсветкой",
    material: "Дуб · металл · подсветка",
    note: "Визуальный пример дизайна, не фотография выполненного объекта",
    isReal: false,
  },
] as const;

