-- CreateTable
CREATE TABLE "Settings" (
    "id" INTEGER NOT NULL DEFAULT 1,
    "pinePrice" INTEGER NOT NULL DEFAULT 65000,
    "elmPrice" INTEGER NOT NULL DEFAULT 85000,
    "oakPrice" INTEGER NOT NULL DEFAULT 110000,
    "woodRailing" INTEGER NOT NULL DEFAULT 650000,
    "glassRailing" INTEGER NOT NULL DEFAULT 900000,
    "brassRailing" INTEGER NOT NULL DEFAULT 1800000,
    "ledPrice" INTEGER NOT NULL DEFAULT 250000,
    "paintingPrice" INTEGER NOT NULL DEFAULT 300000,
    "installationPrice" INTEGER NOT NULL DEFAULT 350000,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Settings_pkey" PRIMARY KEY ("id")
);
