ALTER TYPE "CalendarTaskWorkflow" ADD VALUE IF NOT EXISTS 'DAILY_CRM_REPORT';
ALTER TYPE "CalendarTaskWorkflow" ADD VALUE IF NOT EXISTS 'ORDER_DATA_COMPLETION';
ALTER TYPE "CalendarTaskWorkflow" ADD VALUE IF NOT EXISTS 'PLATFORM_ORIENTATION';
