import assert from "node:assert/strict";
import { detectControlIssues, type ControlLead, type ControlOrder } from "../lib/control/rules";
const now = new Date("2026-10-02T04:00:00Z");
const lead: ControlLead = { id: 1, name: "Клиент", managerUserId: 4, createdAt: new Date("2026-09-30T04:00:00Z"), nextContactAt: new Date("2026-10-03T04:00:00Z"), nextActions: [], interactions: [] };
assert.match(detectControlIssues([lead], [], now)[0].reason, /нет записи о контакте/);
assert.equal(detectControlIssues([{ ...lead, interactions: [{ createdAt: now }] }], [], now).length, 0);
assert.equal(detectControlIssues([{ ...lead, nextActions: [{ nextActionAt: now, completedAt: now, resultComment: "Клиент ответил", nextActionType: "CALL" }] }], [], now).length, 0, "Recorded call results count as contact evidence");
assert.match(detectControlIssues([{ ...lead, nextActions: [{ nextActionAt: new Date("2026-09-30") }] }], [], now)[0].reason, /Просрочено/);
const order: ControlOrder = { id: 2, number: "ORDER-2", clientId: 1, managerUserId: 4, partnerId: null, partnerPrice: 0, partnerAgreedAt: null, promisedAt: new Date("2026-10-03"), productionDeadline: null, lifecycle: "CREATED", client: { phone: "70000000000", city: "Алматы" } };
assert.equal(detectControlIssues([], [order], now).length, 0, "A draft must not require production price");
assert.match(detectControlIssues([], [{ ...order, lifecycle: "IN_PRODUCTION" }], now)[0].reason, /цена производства/);
assert.equal(detectControlIssues([], [{ ...order, promisedAt: new Date("2026-10-01") }], now)[0].priority, "URGENT");
console.log("Founder control evidence and stage rules passed");
