import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { changePercent, paymentEffect, resolveReportRange, safePercent } from "../lib/reports";

const now = new Date("2026-08-08T18:30:00.000Z"); // 23:30 in Almaty
const today = resolveReportRange(new URLSearchParams("period=today"), now);
assert.equal(today.dateFrom, "2026-08-08");
assert.equal(today.start.toISOString(), "2026-08-07T19:00:00.000Z");
assert.equal(today.end.toISOString(), "2026-08-08T18:59:59.999Z");

const week = resolveReportRange(new URLSearchParams("period=week"), now);
assert.equal(week.dateFrom, "2026-08-03");
assert.equal(week.dateTo, "2026-08-08");
const month = resolveReportRange(new URLSearchParams("period=month"), now);
assert.equal(month.dateFrom, "2026-08-01");
assert.equal(month.previousEnd.getTime() + 1, month.start.getTime());
assert.equal(month.end.getTime() - month.start.getTime(), month.previousEnd.getTime() - month.previousStart.getTime());
const quarter = resolveReportRange(new URLSearchParams("period=quarter"), now);
assert.equal(quarter.dateFrom, "2026-07-01");
const year = resolveReportRange(new URLSearchParams("period=year"), now);
assert.equal(year.dateFrom, "2026-01-01");

const custom = resolveReportRange(new URLSearchParams("period=custom&dateFrom=2026-07-10&dateTo=2026-07-12"), now);
assert.equal(custom.start.toISOString(), "2026-07-09T19:00:00.000Z");
assert.throws(() => resolveReportRange(new URLSearchParams("period=custom&dateFrom=2026-08-09&dateTo=2026-08-08"), now));
assert.equal(safePercent(2, 5), 40);
assert.equal(safePercent(2, 0), null);
assert.equal(changePercent(15, 10), 50);
assert.equal(changePercent(10, 0), null);
assert.equal(paymentEffect("CLIENT_PAYMENT", 1_000), 1_000);
assert.equal(paymentEffect("REFUND", 250), -250);
assert.equal(paymentEffect("PARTNER_PAYOUT", 500), 0);

const service = readFileSync(new URL("../lib/services/report.service.ts", import.meta.url), "utf8");
const companyFinance = readFileSync(new URL("../lib/services/management-finance.service.ts", import.meta.url), "utf8");
const route = readFileSync(new URL("../app/api/reports/route.ts", import.meta.url), "utf8");
assert.match(service, /actor\.role === Role\.MANAGER\) scope = \{ managerUserId: actor\.id \}/, "manager scope must ignore spoofed managerId");
assert.match(service, /lifecycle: \{ not: "CANCELLED" \}/, "cancelled orders must be excluded");
assert.match(service, /leadership\(actor\.role\) \? \{ grossMargin, ordersWithMargin: pricedOrders\.length \} : \{\}/, "gross margin must be leadership-only");
assert.match(service, /includeFullDetails = params\.get\("export"\) === "csv"/, "CSV export must keep complete report details");
assert.match(service, /visibleCompletionTasks = includeFullDetails \? completionTasks : completionTasks\.slice\(0, 20\)/, "interactive report must cap completion details");
assert.match(service, /visibleOrders = includeFullDetails \? orders : orders\.slice\(0, 20\)/, "interactive report must cap order details");
assert.match(service, /missingProductionPrice/, "report must expose production-price completeness");
assert.match(service, /completionTasks/, "report must include exact completion tasks by order");
assert.match(service, /recordedExpenses/, "report must include recorded expenses");
assert.match(service, /const pricedOrders = orders\.filter/, "margin must use only orders with complete sale and production prices");
assert.match(service, /const grossMargin = pricedSales - productionCost/, "gross margin must remain available for complete orders");
assert.match(service, /netProfit: actor.role === Role.OPERATIONS_DIRECTOR \|\| pricedOrders.length !== orders.length \? null : netProfit/, "incomplete totals must not be exposed as company net profit");
assert.match(service, /prisma.order.findMany\(\{ where: \{ ...activeOrder, orderReceivedAt: range\(period.start, period.end\)/, "sales month follows business order date, not data-entry date");
assert.match(service, /const key = day\(item.orderReceivedAt\)/, "sales trend follows the same business date");
assert.doesNotMatch(service, /prisma.order.findMany\(\{ where: \{ ...activeOrder, createdAt:/);
assert.match(service, /JOIN "PayrollPeriod" payroll_period ON payroll_period\.id = accrual\."periodId"/, "payroll accruals must follow their accounting period");
assert.match(service, /payroll_period\.year \* 100 \+ payroll_period\.month/, "report payroll period must match the selected business months");
assert.doesNotMatch(service, /accrual\."createdAt" >=/, "late-entered payroll must not move into the wrong reporting month");
const reportPage = readFileSync(new URL("../components/pages/ReportsPage.tsx", import.meta.url), "utf8");
assert.match(reportPage, /Заказы \/ заявки периода/);
assert.match(companyFinance, /lifecycle: "COMPLETED"[\s\S]*partnerPrice: \{ gte: 2 \}[\s\S]*partnerAgreedAt: \{ not: null \}/, "company profit must reject placeholder production prices");
assert.match(route, /requirePermission\("reports"\)/, "reports API must require permission");
assert.match(route, /report\.sales\.grossMargin === undefined/, "export must redact gross margin");
console.log("Reports math, period boundaries, refunds, zero denominators and RBAC contracts: OK");
