"use client";
import { useCallback, useEffect, useState } from "react";
type Approval = { id: number; status: string; managerName: string; standardSalePrice: string; currentSalePrice: string; requestedSalePrice: string; approvedSalePrice?: string; reason: string; comment?: string; client: { name: string; phone: string } };
const money = (value: string | number) => `${Number(value).toLocaleString("ru-RU")} ₸`;
export default function PriceApprovalsPage() {
  const [rows, setRows] = useState<Approval[]>([]), [message, setMessage] = useState("");
  const load = useCallback(async () => { const response = await fetch("/api/price-approvals", { cache: "no-store" }); const body = await response.json(); if (response.ok) setRows(body); else setMessage(body.error); }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => clearTimeout(timer); }, [load]);
  async function decide(id: number, status: string) { const approvedSalePrice = status === "COUNTER_OFFER" ? Number(window.prompt("Встречная цена")) : undefined; const response = await fetch(`/api/price-approvals/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status, approvedSalePrice }) }); const body = await response.json(); setMessage(response.ok ? "Решение сохранено" : body.error); if (response.ok) await load(); }
  return <main className="p-4 md:p-8"><h1 className="text-3xl font-bold text-white">Согласование цен</h1><p className="mt-2 text-slate-400">Запросы менеджеров на специальную цену.</p>{message && <p className="mt-4 rounded-xl bg-slate-900 p-4 text-slate-200">{message}</p>}<div className="mt-6 grid gap-4">{rows.map((row) => <article key={row.id} className="rounded-2xl border border-slate-700 bg-[#101827] p-5 text-slate-200"><div className="flex justify-between gap-3"><div><h2 className="font-semibold text-white">{row.client.name}</h2><p className="text-sm text-slate-400">{row.client.phone} · {row.managerName}</p></div><span>{row.status}</span></div><div className="mt-4 grid gap-2 sm:grid-cols-3"><p>Стандарт: <b>{money(row.standardSalePrice)}</b></p><p>Текущая: <b>{money(row.currentSalePrice)}</b></p><p>Запрошено: <b>{money(row.requestedSalePrice)}</b></p></div><p className="mt-3">Причина: {row.reason}</p>{row.status === "PENDING" && <div className="mt-4 flex flex-wrap gap-2"><button onClick={() => void decide(row.id,"APPROVED")} className="rounded-xl bg-green-700 px-4 py-2">Одобрить</button><button onClick={() => void decide(row.id,"REJECTED")} className="rounded-xl bg-red-800 px-4 py-2">Отклонить</button><button onClick={() => void decide(row.id,"COUNTER_OFFER")} className="rounded-xl bg-amber-600 px-4 py-2 text-black">Предложить другую цену</button></div>}</article>)}</div></main>;
}
