"use client";
/* eslint-disable @next/next/no-img-element -- private authenticated Blob endpoint is intentionally not sent through the public image optimizer */

import { Role } from "@prisma/client";
import { AlertTriangle, Boxes, CircleDollarSign, Grid2X2, ImageIcon, List, PackagePlus } from "lucide-react";
import { useSession } from "next-auth/react";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import type { LucideIcon } from "lucide-react";

type Material = { id:number;code:string|null;name:string;model:string|null;description:string|null;category:string;unit:string;minimumStock:number;stock:number;reserved:number;available:number;purchasePrice?:string;averageCost?:string;inventoryValue?:string;sellingPrice:string;grossProfit?:number;marginPercent?:number;photoUrl:string|null;supplier:string|null;active:boolean };
type Order = { id:number;number:string;client:{name:string} };
type Movement = { id:number;type:string;quantity:number;price?:string;amount?:string;stockDelta:number;reserveDelta:number;comment:string|null;operationAt:string;material:{name:string;unit:string};order:{number:string}|null;employee:{name:string}|null };
type Reservation = { id:number;quantity:number;consumed:number;status:string;updatedAt:string;material:{name:string;unit:string};order:{number:string;client:{name:string}};createdBy:{name:string}|null };
type Data = { materials:Material[];orders:Order[];movements:Movement[];reservations:Reservation[];pagination:{page:number;pages:number};materialPagination:{page:number;pages:number};stats:{materials:number;inStock:number;outOfStock:number;lowStock:number;stockValue?:number;potentialSales?:number;potentialGrossProfit?:number;reserved:number;available:number;suppliers:string[];categories:string[]} };
const empty:Data={materials:[],orders:[],movements:[],reservations:[],pagination:{page:1,pages:0},materialPagination:{page:1,pages:0},stats:{materials:0,inStock:0,outOfStock:0,lowStock:0,reserved:0,available:0,suppliers:[],categories:[]}};
const blank={name:"",model:"",description:"",category:"Латунь",unit:"шт",minimumStock:"0",initialStock:"0",purchasePrice:"0",sellingPrice:"0",supplier:"",active:true};
const operationBlank={type:"incoming",materialId:"",orderId:"",quantity:"",price:"",supplier:"",comment:""};
const labels:Record<string,string>={incoming:"Приход",outgoing:"Расход",adjustment:"Корректировка",return:"Возврат",reserve:"Резерв",release:"Снятие резерва",consume:"Списание"};
const money=(value:number|string|undefined)=>`${Number(value??0).toLocaleString("ru-RU")} ₸`;

export default function WarehousePage(){
  const {data:session}=useSession(); const role=session?.user.role as Role|undefined;
  const canCost=role===Role.DIRECTOR||role===Role.ACCOUNTANT, canCreate=role===Role.DIRECTOR, canEdit=canCost;
  const [data,setData]=useState(empty),[tab,setTab]=useState("items"),[view,setView]=useState<"cards"|"table">("cards"),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
  const [search,setSearch]=useState(""),[query,setQuery]=useState(""),[category,setCategory]=useState(""),[status,setStatus]=useState(""),[itemPage,setItemPage]=useState(1),[historyPage,setHistoryPage]=useState(1);
  const [form,setForm]=useState(blank),[editing,setEditing]=useState<Material|null>(null),[photo,setPhoto]=useState<File|null>(null),[operation,setOperation]=useState(operationBlank);
  useEffect(()=>{const id=window.setTimeout(()=>{setQuery(search);setItemPage(1)},300);return()=>window.clearTimeout(id)},[search]);
  const load=useCallback(async()=>{setLoading(true);try{const p=new URLSearchParams({materialPage:String(itemPage),materialPageSize:"48",page:String(historyPage),pageSize:"25"});if(query)p.set("search",query);if(category)p.set("category",category);if(status)p.set("stockStatus",status);const response=await fetch(`/api/warehouse?${p}`,{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error??"Не удалось загрузить склад");setData(body)}catch(cause){setError(cause instanceof Error?cause.message:"Ошибка склада")}finally{setLoading(false)}},[itemPage,historyPage,query,category,status]);
  useEffect(()=>{const id=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(id)},[load]);
  async function request(method:"POST"|"PATCH",body:unknown){const response=await fetch("/api/warehouse",{method,headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error??"Операция не выполнена");return result as {id:number};}
  async function saveItem(event:FormEvent){event.preventDefault();setSaving(true);setError("");try{const payload={name:form.name,model:form.model,description:form.description,category:form.category,unit:form.unit,minimumStock:form.minimumStock,purchasePrice:form.purchasePrice,sellingPrice:form.sellingPrice,supplier:form.supplier};const result=editing?await request("PATCH",{id:editing.id,...payload,active:form.active}):await request("POST",{action:"material",...payload,initialStock:form.initialStock});if(photo){const fd=new FormData();fd.set("file",photo);const upload=await fetch(`/api/warehouse/${result.id}/photo`,{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},body:fd});if(!upload.ok)throw new Error((await upload.json()).error??"Товар создан, но фото не загружено")}setForm(blank);setEditing(null);setPhoto(null);await load()}catch(cause){setError(cause instanceof Error?cause.message:"Ошибка сохранения")}finally{setSaving(false)}}
  async function saveOperation(event:FormEvent){event.preventDefault();setSaving(true);setError("");try{await request("POST",{action:"operation",...operation,orderId:operation.orderId||undefined,price:operation.price||undefined,supplier:operation.supplier||undefined});setOperation(operationBlank);await load()}catch(cause){setError(cause instanceof Error?cause.message:"Ошибка операции")}finally{setSaving(false)}}
  function edit(item:Material){setEditing(item);setForm({name:item.name,model:item.model??"",description:item.description??"",category:item.category,unit:item.unit,minimumStock:String(item.minimumStock),initialStock:"0",purchasePrice:String(item.purchasePrice??0),sellingPrice:String(item.sellingPrice),supplier:item.supplier??"",active:item.active});window.scrollTo({top:0,behavior:"smooth"})}
  const visible=useMemo(()=>data.materials.filter(x=>status!=="low"||(x.available>0&&x.available<=x.minimumStock)).filter(x=>status!=="in-stock"||x.available>0),[data.materials,status]);
  const operationOptions=role===Role.ACCOUNTANT?["incoming","adjustment","return"]:role===Role.MANAGER?["reserve","release"]:role===Role.PRODUCTION||role===Role.INSTALLER?["consume"]:["incoming","outgoing","adjustment","return","reserve","release","consume"];
  const summaries:Array<[LucideIcon,string,number]>=[[Boxes,"Позиций",data.stats.materials],[Boxes,"В наличии",data.stats.inStock],[AlertTriangle,"Заканчивается",data.stats.lowStock],[PackagePlus,"Нет в наличии",data.stats.outOfStock]];
  return <section className="min-h-screen flex-1 overflow-x-hidden bg-[#0b1120] p-4 text-white md:p-8">
    <header><h1 className="text-3xl font-bold">Склад</h1><p className="mt-2 text-slate-400">Офис / Шоурум · товарные остатки</p></header>
    {error&&<p className="my-4 rounded-xl border border-red-800 bg-red-950/50 p-4 text-red-200">{error}</p>}
    <div className="my-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{summaries.map(([Icon,title,value])=><div key={title} className="rounded-2xl border border-slate-800 bg-[#101827] p-5"><Icon className="mb-3 text-blue-400"/><p className="text-sm text-slate-400">{title}</p><b className="text-2xl">{value}</b></div>)}{canCost&&[["Стоимость остатков",data.stats.stockValue],["Потенциальная сумма продажи",data.stats.potentialSales],["Потенциальная валовая прибыль",data.stats.potentialGrossProfit]].map(([title,value])=><div key={String(title)} className="rounded-2xl border border-emerald-900 bg-emerald-950/20 p-5"><CircleDollarSign className="mb-3 text-emerald-400"/><p className="text-sm text-slate-400">{title}</p><b className="text-xl">{money(value as number)}</b></div>)}</div>
    <nav className="mb-5 flex gap-2 overflow-x-auto">{[["items","Товары"],["operations","Операции"],["reservations","Резервы"],["history","История"]].map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`whitespace-nowrap rounded-xl px-4 py-2 ${tab===id?"bg-blue-600":"bg-slate-800 text-slate-300"}`}>{label}</button>)}</nav>
    {tab==="items"&&<div className="space-y-5">
      {(canCreate||editing)&&<form onSubmit={saveItem} className="grid gap-3 rounded-2xl border border-slate-800 bg-[#101827] p-5 md:grid-cols-3"><h2 className="text-xl font-bold md:col-span-3">{editing?`Редактирование ${editing.code}`:"Добавить товар"}</h2>{(["name","model","category","unit","minimumStock","sellingPrice"] as const).map(key=><input key={key} required={["name","category","unit"].includes(key)} type={["minimumStock","sellingPrice"].includes(key)?"number":"text"} min="0" step="any" value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} placeholder={{name:"Название",model:"Модель / артикул",category:"Категория",unit:"Единица",minimumStock:"Минимальный остаток",sellingPrice:"Продажная цена"}[key]} className="rounded-xl border border-slate-700 bg-slate-900 p-3"/>)}{canCost&&<><input type="number" min="0" step="any" value={form.purchasePrice} onChange={e=>setForm({...form,purchasePrice:e.target.value})} placeholder="Закупочная цена" className="rounded-xl border border-slate-700 bg-slate-900 p-3"/><input value={form.supplier} onChange={e=>setForm({...form,supplier:e.target.value})} placeholder="Поставщик" className="rounded-xl border border-slate-700 bg-slate-900 p-3"/></>}{!editing&&<input type="number" min="0" step="any" value={form.initialStock} onChange={e=>setForm({...form,initialStock:e.target.value})} placeholder="Начальный остаток" className="rounded-xl border border-slate-700 bg-slate-900 p-3"/>}<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Описание / комментарий" className="rounded-xl border border-slate-700 bg-slate-900 p-3 md:col-span-2"/><label className="rounded-xl border border-dashed border-slate-600 p-3 text-sm text-slate-300">Фото JPG/PNG/WEBP<input className="mt-2 block w-full" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setPhoto(e.target.files?.[0]??null)}/></label><button disabled={saving} className="rounded-xl bg-blue-600 p-3 font-semibold disabled:opacity-50">{saving?"Сохранение…":"Сохранить"}</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(blank);setPhoto(null)}} className="rounded-xl bg-slate-700 p-3">Отмена</button>}</form>}
      <div className="grid gap-3 rounded-2xl border border-slate-800 bg-[#101827] p-4 md:grid-cols-5"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Код, название, модель" className="rounded-xl bg-slate-900 p-3"/><select value={category} onChange={e=>{setCategory(e.target.value);setItemPage(1)}} className="rounded-xl bg-slate-900 p-3"><option value="">Все категории</option>{data.stats.categories.map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl bg-slate-900 p-3"><option value="">Все остатки</option><option value="in-stock">В наличии</option><option value="low">Заканчивается</option><option value="out">Нет в наличии</option><option value="reserved">Есть резерв</option></select><div className="hidden md:block"/><div className="hidden justify-end gap-2 md:flex"><button onClick={()=>setView("cards")} className={`rounded-lg p-3 ${view==="cards"?"bg-blue-600":"bg-slate-800"}`}><Grid2X2/></button><button onClick={()=>setView("table")} className={`rounded-lg p-3 ${view==="table"?"bg-blue-600":"bg-slate-800"}`}><List/></button></div></div>
      {loading?<p className="rounded-2xl bg-[#101827] p-8 text-slate-400">Загрузка…</p>:<>{view==="cards"&&<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{visible.map(item=><article key={item.id} className="overflow-hidden rounded-2xl border border-slate-800 bg-[#101827]"><div className="aspect-[4/3] bg-slate-900">{item.photoUrl?<img src={item.photoUrl} alt={item.name} className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center text-slate-600"><ImageIcon size={52}/></div>}</div><div className="p-4"><p className="font-mono text-sm font-bold text-blue-400">{item.code??`MAT-${item.id}`}</p><h3 className="mt-1 text-lg font-bold">{item.name}</h3><p className="text-sm text-slate-400">{item.model||item.category}</p><div className="mt-4 flex items-end justify-between"><div><b className="text-2xl">{item.available} <small className="text-sm font-normal text-slate-400">{item.unit}</small></b><p className={item.available<=0?"text-red-400":item.available<=item.minimumStock?"text-amber-400":"text-emerald-400"}>{item.available<=0?"Нет в наличии":item.available<=item.minimumStock?"Заканчивается":"В наличии"}</p></div><b>{money(item.sellingPrice)}</b></div><p className="mt-2 text-xs text-slate-500">В наличии {item.stock} · резерв {item.reserved}</p>{canCost&&<div className="mt-3 grid grid-cols-2 rounded-xl bg-slate-900 p-3 text-xs text-slate-400"><span>Себестоимость<br/><b className="text-white">{money(item.averageCost)}</b></span><span>Маржа<br/><b className="text-white">{(item.marginPercent??0).toFixed(1)}%</b></span></div>}{canEdit&&<button onClick={()=>edit(item)} className="mt-4 w-full rounded-xl bg-blue-600 p-2 font-semibold">Открыть</button>}</div></article>)}</div>}{view==="table"&&<div className="hidden overflow-x-auto rounded-2xl border border-slate-800 md:block"><table className="w-full min-w-[800px] text-left"><thead className="bg-slate-900 text-slate-400"><tr><th className="p-4">Товар</th><th>Категория</th><th>В наличии</th><th>Резерв</th><th>Доступно</th><th>Продажная цена</th><th/></tr></thead><tbody>{visible.map(x=><tr key={x.id} className="border-t border-slate-800"><td className="p-4"><b>{x.code}</b><span className="block text-sm text-slate-400">{x.name}</span></td><td>{x.category}</td><td>{x.stock}</td><td>{x.reserved}</td><td>{x.available}</td><td>{money(x.sellingPrice)}</td><td>{canEdit&&<button onClick={()=>edit(x)} className="rounded-lg bg-blue-700 px-3 py-2">Открыть</button>}</td></tr>)}</tbody></table></div>}</>}
      <div className="flex justify-between"><button disabled={itemPage<=1} onClick={()=>setItemPage(x=>x-1)} className="rounded-lg bg-slate-800 px-4 py-2 disabled:opacity-40">Назад</button><span className="text-slate-400">{itemPage} / {Math.max(1,data.materialPagination.pages)}</span><button disabled={itemPage>=data.materialPagination.pages} onClick={()=>setItemPage(x=>x+1)} className="rounded-lg bg-slate-800 px-4 py-2 disabled:opacity-40">Далее</button></div>
    </div>}
    {tab==="operations"&&<form onSubmit={saveOperation} className="grid gap-3 rounded-2xl border border-slate-800 bg-[#101827] p-6 md:grid-cols-2"><h2 className="text-xl font-bold md:col-span-2">Новая операция</h2><select value={operation.type} onChange={e=>setOperation({...operation,type:e.target.value})} className="rounded-xl bg-slate-900 p-3">{operationOptions.map(x=><option key={x} value={x}>{labels[x]}</option>)}</select><select required value={operation.materialId} onChange={e=>setOperation({...operation,materialId:e.target.value})} className="rounded-xl bg-slate-900 p-3"><option value="">Товар</option>{data.materials.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name} · доступно {x.available}</option>)}</select>{["reserve","release","consume","outgoing"].includes(operation.type)&&<select required={["reserve","release","consume"].includes(operation.type)} value={operation.orderId} onChange={e=>setOperation({...operation,orderId:e.target.value})} className="rounded-xl bg-slate-900 p-3"><option value="">Заказ</option>{data.orders.map(x=><option key={x.id} value={x.id}>{x.number} — {x.client.name}</option>)}</select>}<input required type="number" min="0" step="any" value={operation.quantity} onChange={e=>setOperation({...operation,quantity:e.target.value})} placeholder={operation.type==="adjustment"?"Новый остаток":"Количество"} className="rounded-xl bg-slate-900 p-3"/>{canCost&&<input type="number" min="0" step="any" value={operation.price} onChange={e=>setOperation({...operation,price:e.target.value})} placeholder="Цена" className="rounded-xl bg-slate-900 p-3"/>}<input value={operation.comment} onChange={e=>setOperation({...operation,comment:e.target.value})} placeholder={operation.type==="consume"?"Причина списания":"Комментарий"} className="rounded-xl bg-slate-900 p-3"/><button disabled={saving} className="rounded-xl bg-blue-600 p-3 font-semibold">Выполнить</button></form>}
    {tab==="reservations"&&<div className="space-y-3">{data.reservations.map(x=><div key={x.id} className="rounded-2xl border border-slate-800 bg-[#101827] p-4"><b>Заказ №{x.order.number}</b><p className="text-slate-400">{x.order.client.name} · {x.material.name}</p><p className="mt-2">{x.quantity-x.consumed} {x.material.unit} · {x.status}</p></div>)}</div>}
    {tab==="history"&&<div className="space-y-3">{data.movements.map(x=><div key={x.id} className="rounded-2xl border border-slate-800 bg-[#101827] p-4"><div className="flex flex-wrap justify-between gap-2"><b>{labels[x.type]??x.type} · {x.material.name}</b><time className="text-sm text-slate-400">{new Date(x.operationAt).toLocaleString("ru-RU")}</time></div><p className="mt-2">{x.stockDelta||x.reserveDelta} {x.material.unit}{x.order?` · Заказ №${x.order.number}`:""}</p>{canCost&&x.amount!==undefined&&<p className="text-sm text-slate-400">{money(x.amount)}</p>}{x.comment&&<p className="text-sm text-slate-400">{x.comment}</p>}</div>)}<div className="flex justify-between"><button disabled={historyPage<=1} onClick={()=>setHistoryPage(x=>x-1)} className="rounded-lg bg-slate-800 px-4 py-2 disabled:opacity-40">Назад</button><button disabled={historyPage>=data.pagination.pages} onClick={()=>setHistoryPage(x=>x+1)} className="rounded-lg bg-slate-800 px-4 py-2 disabled:opacity-40">Далее</button></div></div>}
  </section>
}
