"use client";

import Link from "next/link";
import { useSession } from "next-auth/react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Banknote, CheckCircle2, ClipboardCheck, FileImage, MapPin, MessageCircle, Phone, Play, Save, Upload } from "lucide-react";

type Photo = { id: number; type: string; fileName: string; contentType: string; size: number };
type Measurement = {
  id: number; status: string; visitDate: string; city: string; address: string; mapLink?: string | null; managerComment?: string | null;
  stepsCount?: number | null; sameSize: boolean; stepLength?: number | null; stepWidth?: number | null; stepHeight?: number | null;
  individualSteps?: Array<{ length: number; width: number; height?: number }> | null; riserHeight?: number | null; winderCount: number;
  winders?: Array<{ length?: number; width?: number; comment?: string }> | null; platformsCount: number; platforms?: Array<{ length: number; width: number }> | null;
  railingLength?: number | null; railingComment?: string | null; objectNotes?: string | null; comment?: string | null;
  client: { id: number; name: string; phone: string; whatsapp: string; city: string; address: string };
  measurerUser?: { id: number; name: string } | null; attachments: Photo[]; order?: { id: number; number: string } | null;
  bonusAccrual?: { id: number; amount: string; orderId: number } | null;
};
type Payload = { measurements: Measurement[]; kpi: { today: number; upcoming: number; overdue: number; handed: number; monthCompleted: number; monthOrders: number; monthBonus: number; payable: number } };
type Form = { stepsCount: string; sameSize: boolean; stepLength: string; stepWidth: string; stepHeight: string; individualSteps: string; riserHeight: string; winderCount: string; winders: string; platformsCount: string; platforms: string; railingLength: string; railingComment: string; objectNotes: string; comment: string };

const input = "min-h-11 w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2 text-white outline-none focus:border-blue-500";
const statusNames: Record<string, string> = { ASSIGNED: "Назначен", IN_PROGRESS: "В работе", COMPLETED: "Завершён", HANDED_TO_MANAGER: "Передан менеджеру", CANCELLED: "Отменён" };
const statusTone: Record<string, string> = { ASSIGNED: "bg-blue-950 text-blue-200", IN_PROGRESS: "bg-amber-950 text-amber-200", COMPLETED: "bg-emerald-950 text-emerald-200", HANDED_TO_MANAGER: "bg-violet-950 text-violet-200", CANCELLED: "bg-slate-800 text-slate-300" };
const money = (value: number) => `${value.toLocaleString("ru-RU")} ₸`;
const when = (value: string) => new Intl.DateTimeFormat("ru-RU", { timeZone: "Asia/Almaty", dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
const time = (value: string) => new Intl.DateTimeFormat("ru-RU", { timeZone: "Asia/Almaty", hour: "2-digit", minute: "2-digit" }).format(new Date(value));
const businessDate = (value: string | Date) => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Almaty", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date(value));
const empty = (): Form => ({ stepsCount: "", sameSize: true, stepLength: "", stepWidth: "", stepHeight: "", individualSteps: "", riserHeight: "", winderCount: "0", winders: "", platformsCount: "0", platforms: "", railingLength: "", railingComment: "", objectNotes: "", comment: "" });
const formOf = (row: Measurement): Form => ({ stepsCount: String(row.stepsCount ?? ""), sameSize: row.sameSize, stepLength: String(row.stepLength ?? ""), stepWidth: String(row.stepWidth ?? ""), stepHeight: String(row.stepHeight ?? ""), individualSteps: row.individualSteps?.map((item) => `${item.length} x ${item.width}${item.height ? ` x ${item.height}` : ""}`).join("\n") ?? "", riserHeight: String(row.riserHeight ?? ""), winderCount: String(row.winderCount ?? 0), winders: row.winders?.map((item) => `${item.length ?? ""} x ${item.width ?? ""}${item.comment ? ` — ${item.comment}` : ""}`).join("\n") ?? "", platformsCount: String(row.platformsCount ?? 0), platforms: row.platforms?.map((item) => `${item.length} x ${item.width}`).join("\n") ?? "", railingLength: String(row.railingLength ?? ""), railingComment: row.railingComment ?? "", objectNotes: row.objectNotes ?? "", comment: row.comment ?? "" });

function dimensions(value: string, withComment = false) {
  return value.split("\n").map((line) => line.trim()).filter(Boolean).map((line) => {
    const [size, note] = line.split(/\s+[—-]\s+/, 2), numbers = size.split(/[xх×]/i).map(Number);
    return { length: numbers[0], width: numbers[1], ...(numbers[2] ? { height: numbers[2] } : {}), ...(withComment && note ? { comment: note } : {}) };
  });
}

export default function MeasurementWorkspace() {
  const { data: session } = useSession();
  const [data, setData] = useState<Payload>({ measurements: [], kpi: { today: 0, upcoming: 0, overdue: 0, handed: 0, monthCompleted: 0, monthOrders: 0, monthBonus: 0, payable: 0 } });
  const [tab, setTab] = useState<"today" | "upcoming" | "completed">("today"), [selectedId, setSelectedId] = useState<number | null>(null), [form, setForm] = useState<Form>(empty()), [busy, setBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const photoRef = useRef<HTMLInputElement>(null), [photoType, setPhotoType] = useState("SHEET");
  const measurer = session?.user.role === "MEASURER";
  const load = useCallback(async () => { const response = await fetch("/api/measurements?workspace=1", { cache: "no-store" }), body = await response.json().catch(() => ({})); if (!response.ok) setError(body.error ?? "Не удалось загрузить замеры"); else setData(body); }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const selected = data.measurements.find((row) => row.id === selectedId) ?? null;
  const rows = useMemo(() => { const now = new Date(), today = businessDate(now); return data.measurements.filter((row) => tab === "today" ? businessDate(row.visitDate) === today && row.status !== "CANCELLED" : tab === "upcoming" ? new Date(row.visitDate) > now && ["ASSIGNED", "IN_PROGRESS"].includes(row.status) : ["COMPLETED", "HANDED_TO_MANAGER"].includes(row.status)).sort((a, b) => new Date(a.visitDate).getTime() - new Date(b.visitDate).getTime()); }, [data.measurements, tab]);
  const patchForm = (key: keyof Form, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }));
  const payload = (action: string) => ({ action, stepsCount: Number(form.stepsCount || 0), sameSize: form.sameSize, stepLength: form.stepLength ? Number(form.stepLength) : undefined, stepWidth: form.stepWidth ? Number(form.stepWidth) : undefined, stepHeight: form.stepHeight ? Number(form.stepHeight) : undefined, individualSteps: dimensions(form.individualSteps), riserHeight: form.riserHeight ? Number(form.riserHeight) : undefined, winderCount: Number(form.winderCount || 0), winders: dimensions(form.winders, true), platformsCount: Number(form.platformsCount || 0), platforms: dimensions(form.platforms), railingLength: form.railingLength ? Number(form.railingLength) : undefined, railingComment: form.railingComment, objectNotes: form.objectNotes, comment: form.comment });
  async function run(body: Record<string, unknown>, ok: string) { if (!selected) return; setBusy(true); setError(""); setNotice(""); const response = await fetch(`/api/measurements/${selected.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }), result = await response.json().catch(() => ({})); if (!response.ok) setError(result.error ?? "Не удалось выполнить действие"); else { setNotice(ok); await load(); } setBusy(false); }
  async function upload(file?: File) { if (!selected || !file) return; setBusy(true); setError(""); const body = new FormData(); body.set("file", file); body.set("type", photoType); const response = await fetch(`/api/measurements/${selected.id}/attachments`, { method: "POST", body }), result = await response.json().catch(() => ({})); if (!response.ok) setError(result.error ?? "Не удалось загрузить фото"); else { setNotice("Фото сохранено в замере"); await load(); } if (photoRef.current) photoRef.current.value = ""; setBusy(false); }
  return <main className="space-y-5 p-4 pb-24 md:p-8">
    <header className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-bold text-white md:text-3xl">Кабинет замерщика</h1><p className="mt-1 text-sm text-slate-400">Расписание, фактические размеры и передача результата менеджеру</p></div>{measurer && <Link href="/payroll" className="flex min-h-11 items-center gap-2 rounded-xl bg-slate-800 px-4 text-sm text-white"><Banknote size={17}/>Моя зарплата</Link>}</header>
    {error && <p role="alert" className="rounded-xl border border-red-800 bg-red-950/40 p-4 text-red-300">{error}</p>}{notice && <p role="status" className="rounded-xl border border-emerald-800 bg-emerald-950/40 p-4 text-emerald-300">{notice}</p>}
    <section className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Kpi title="Сегодня" value={data.kpi.today}/><Kpi title="Предстоящие" value={data.kpi.upcoming}/><Kpi title="Просрочены" value={data.kpi.overdue} alert/><Kpi title="Передано за месяц" value={data.kpi.handed}/></section>
    {measurer && <section className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Kpi title="Замеров за месяц" value={data.kpi.monthCompleted}/><Kpi title="Заказов после замера" value={data.kpi.monthOrders}/><Kpi title="Бонус за замеры" value={money(data.kpi.monthBonus)}/><Kpi title="К выплате" value={money(data.kpi.payable)}/></section>}
    <div className="grid gap-5 xl:grid-cols-[minmax(300px,0.8fr)_minmax(0,1.5fr)]">
      <section className="rounded-2xl border border-slate-800 bg-[#101827] p-4"><div className="grid grid-cols-3 gap-2">{([['today','Сегодня'],['upcoming','Предстоящие'],['completed','Завершённые']] as const).map(([value, title]) => <button key={value} onClick={() => setTab(value)} className={`min-h-11 rounded-xl px-2 text-sm ${tab === value ? "bg-blue-600 text-white" : "bg-slate-900 text-slate-300"}`}>{title}</button>)}</div><div className="mt-4 space-y-3">{rows.length ? rows.map((row) => <button key={row.id} onClick={() => { setSelectedId(row.id); setForm(formOf(row)); }} className={`w-full rounded-xl border p-4 text-left ${selectedId === row.id ? "border-blue-500 bg-blue-950/30" : "border-slate-800 bg-slate-950/60"}`}><div className="flex items-start justify-between gap-3"><span className="text-lg font-bold text-white">{time(row.visitDate)}</span><span className={`rounded-full px-2 py-1 text-xs ${statusTone[row.status]}`}>{statusNames[row.status]}</span></div><b className="mt-2 block break-words text-slate-100">{row.client.name}</b><span className="mt-1 block text-sm text-slate-400">{row.city} · {row.address || "Локация по ссылке"}</span></button>) : <p className="rounded-xl border border-dashed border-slate-700 p-5 text-center text-slate-400">Замеров в этой группе нет.</p>}</div></section>
      {!selected ? <section className="grid min-h-80 place-items-center rounded-2xl border border-dashed border-slate-700 p-6 text-center text-slate-400">Выберите замер в расписании.</section> : <section className="space-y-5 rounded-2xl border border-slate-800 bg-[#101827] p-4 md:p-6">
        <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm text-blue-300">Замер №{selected.id} · {when(selected.visitDate)}</p><h2 className="mt-1 text-2xl font-bold text-white">{selected.client.name}</h2><p className="mt-1 text-slate-400">{selected.city} · {selected.address}</p></div><span className={`rounded-full px-3 py-1 text-sm ${statusTone[selected.status]}`}>{statusNames[selected.status]}</span></div>
        <div className="grid grid-cols-2 gap-2 sm:flex sm:flex-wrap"><a href={`tel:${selected.client.phone}`} className="flex min-h-12 items-center justify-center gap-2 rounded-xl bg-slate-800 px-4"><Phone size={18}/>Позвонить</a><a href={`https://wa.me/${(selected.client.whatsapp || selected.client.phone).replace(/\D/g, "")}`} target="_blank" rel="noreferrer" className="flex min-h-12 items-center justify-center gap-2 rounded-xl bg-green-700 px-4"><MessageCircle size={18}/>WhatsApp</a>{(selected.mapLink || selected.address) && <a href={selected.mapLink || `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${selected.city} ${selected.address}`)}`} target="_blank" rel="noreferrer" className="col-span-2 flex min-h-12 items-center justify-center gap-2 rounded-xl bg-blue-800 px-4"><MapPin size={18}/>Открыть карту</a>}</div>
        {selected.managerComment && <p className="rounded-xl bg-slate-900 p-4 text-sm text-slate-300"><b className="text-white">Комментарий менеджера:</b> {selected.managerComment}</p>}
        {measurer && selected.status === "ASSIGNED" && <button disabled={busy} onClick={() => void run({ action: "start" }, "Замер начат")} className="flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-amber-500 font-semibold text-slate-950"><Play size={18}/>Начать замер</button>}
        {measurer && ["ASSIGNED", "IN_PROGRESS"].includes(selected.status) && <><div className="grid gap-4 sm:grid-cols-2"><Field label="Количество ступеней"><input type="number" min="0" inputMode="numeric" className={input} value={form.stepsCount} onChange={(event) => patchForm("stepsCount", event.target.value)}/></Field><label className="flex min-h-11 items-center gap-3 rounded-xl border border-slate-700 px-3 text-sm text-slate-200"><input type="checkbox" checked={form.sameSize} onChange={(event) => patchForm("sameSize", event.target.checked)}/>Все ступени одного размера</label>{form.sameSize ? <><Field label="Длина, мм"><input type="number" className={input} value={form.stepLength} onChange={(event) => patchForm("stepLength", event.target.value)}/></Field><Field label="Ширина, мм"><input type="number" className={input} value={form.stepWidth} onChange={(event) => patchForm("stepWidth", event.target.value)}/></Field><Field label="Высота / толщина, мм"><input type="number" className={input} value={form.stepHeight} onChange={(event) => patchForm("stepHeight", event.target.value)}/></Field></> : <Field label="Каждая ступень: длина x ширина x высота (одна строка)"><textarea rows={5} className={input} value={form.individualSteps} onChange={(event) => patchForm("individualSteps", event.target.value)}/></Field>}<Field label="Высота подступенка, мм"><input type="number" className={input} value={form.riserHeight} onChange={(event) => patchForm("riserHeight", event.target.value)}/></Field><Field label="Забежные ступени, шт"><input type="number" min="0" className={input} value={form.winderCount} onChange={(event) => patchForm("winderCount", event.target.value)}/></Field><Field label="Забежные: длина x ширина — комментарий"><textarea rows={3} className={input} value={form.winders} onChange={(event) => patchForm("winders", event.target.value)}/></Field><Field label="Площадки, шт"><input type="number" min="0" className={input} value={form.platformsCount} onChange={(event) => patchForm("platformsCount", event.target.value)}/></Field><Field label="Площадки: длина x ширина (одна строка)"><textarea rows={3} className={input} value={form.platforms} onChange={(event) => patchForm("platforms", event.target.value)}/></Field><Field label="Длина ограждения, м"><input type="number" step="0.1" className={input} value={form.railingLength} onChange={(event) => patchForm("railingLength", event.target.value)}/></Field><Field label="Комментарий к ограждению"><input className={input} value={form.railingComment} onChange={(event) => patchForm("railingComment", event.target.value)}/></Field><Field label="Особенности объекта"><textarea rows={3} className={input} value={form.objectNotes} onChange={(event) => patchForm("objectNotes", event.target.value)}/></Field><Field label="Комментарий замерщика"><textarea rows={3} className={input} value={form.comment} onChange={(event) => patchForm("comment", event.target.value)}/></Field></div>
          <div className="rounded-xl border border-slate-700 bg-slate-950/60 p-4"><h3 className="font-semibold text-white">Фотографии</h3><p className="mt-1 text-sm text-slate-400">Фото листа замера обязательно для завершения. Файлы сохраняются в закрытом хранилище.</p><div className="mt-3 grid gap-2 sm:grid-cols-[1fr_auto]"><select value={photoType} onChange={(event) => setPhotoType(event.target.value)} className={input}><option value="SHEET">Лист замера</option><option value="OPENING">Проём</option><option value="OBJECT">Объект</option><option value="EXTRA">Дополнительное</option></select><button disabled={busy} onClick={() => photoRef.current?.click()} className="flex min-h-11 items-center justify-center gap-2 rounded-xl bg-blue-700 px-4"><Upload size={17}/>Загрузить</button></div><input ref={photoRef} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => void upload(event.target.files?.[0])}/><PhotoList photos={selected.attachments}/></div>
          <div className="grid gap-2 sm:grid-cols-2"><button disabled={busy} onClick={() => void run(payload("save-draft"), "Черновик сохранён")} className="flex min-h-12 items-center justify-center gap-2 rounded-xl bg-slate-700 font-semibold"><Save size={18}/>Сохранить черновик</button><button disabled={busy} onClick={() => void run(payload("complete"), "Замер завершён; данные зафиксированы")} className="flex min-h-12 items-center justify-center gap-2 rounded-xl bg-emerald-700 font-semibold"><CheckCircle2 size={18}/>Завершить замер</button></div></>}
        {["COMPLETED", "HANDED_TO_MANAGER"].includes(selected.status) && <MeasurementResult row={selected}/>}
        {measurer && selected.status === "COMPLETED" && <button disabled={busy} onClick={() => void run({ action: "handoff" }, "Замер передан менеджеру")} className="flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-violet-700 font-semibold"><ClipboardCheck size={18}/>Передать менеджеру</button>}
      </section>}
    </div>
  </main>;
}

function Kpi({ title, value, alert = false }: { title: string; value: string | number; alert?: boolean }) { return <div className={`rounded-2xl border p-4 ${alert && Number(value) > 0 ? "border-red-800 bg-red-950/30" : "border-slate-800 bg-[#101827]"}`}><p className="text-xs text-slate-400 sm:text-sm">{title}</p><b className="mt-2 block text-xl text-white sm:text-2xl">{value}</b></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm text-slate-300"><span className="mb-1 block">{label}</span>{children}</label>; }
function PhotoList({ photos }: { photos: Photo[] }) { return <div className="mt-3 flex flex-wrap gap-2">{photos.map((photo) => <a key={photo.id} href={`/api/measurement-attachments/${photo.id}`} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-slate-800 px-3 text-sm text-blue-200"><FileImage size={16}/>{photo.type === "SHEET" ? "Лист замера" : photo.fileName}</a>)}</div>; }
function MeasurementResult({ row }: { row: Measurement }) { return <section className="rounded-xl border border-emerald-800/50 bg-emerald-950/10 p-4"><h3 className="font-semibold text-white">Зафиксированный результат</h3><div className="mt-3 grid grid-cols-2 gap-3 text-sm text-slate-300 sm:grid-cols-3"><span>Ступени<br/><b className="text-white">{row.stepsCount ?? 0}</b></span><span>Размер<br/><b className="text-white">{row.sameSize ? `${row.stepLength} × ${row.stepWidth} мм` : "индивидуальный"}</b></span><span>Подступенок<br/><b className="text-white">{row.riserHeight ?? "—"} мм</b></span><span>Забежные<br/><b className="text-white">{row.winderCount}</b></span><span>Площадки<br/><b className="text-white">{row.platformsCount}</b></span><span>Ограждение<br/><b className="text-white">{row.railingLength ?? 0} м</b></span></div>{row.objectNotes && <p className="mt-3 whitespace-pre-wrap text-sm text-slate-300">{row.objectNotes}</p>}<PhotoList photos={row.attachments}/>{row.bonusAccrual && <p className="mt-3 text-sm text-emerald-300">Бонус: {money(Number(row.bonusAccrual.amount))} · заказ #{row.bonusAccrual.orderId}</p>}</section>; }
