"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import StairCalculator from "@/components/calculator/StairCalculator";
import PriceObjectionPanel from "@/components/clients/PriceObjectionPanel";

type Calculation = { id: number; material: string; baseClientPrice: string; clientPrice: string; createdAt: string };
type Proposal = { id: number; number: string; status: string; validUntil: string; executionTerm: string; paymentTerms: string; warranty: string; managerContact: string; snapshot: { company?: { name?: string; phone?: string }; client?: { name?: string; phone?: string; city?: string; request?: string }; calculation?: Record<string, unknown>; clientPrice?: string | number; manager?: string; date?: string }; conversion?: { orderId: number } | null };
const money = (value: string | number) => `${Number(value).toLocaleString("ru-RU")} ₸`;

export default function LeadProposalWorkspace({ clientId, initialCalculationId }: { clientId: number; initialCalculationId?: number }) {
  const router = useRouter();
  const [calculations, setCalculations] = useState<Calculation[]>([]), [proposals, setProposals] = useState<Proposal[]>([]), [calculationId, setCalculationId] = useState(initialCalculationId ? String(initialCalculationId) : ""), [message, setMessage] = useState(""), [saving, setSaving] = useState(false);
  const load = useCallback(async () => { const [a, b] = await Promise.all([fetch(`/api/clients/${clientId}/calculations`, { cache: "no-store" }), fetch(`/api/clients/${clientId}/proposals`, { cache: "no-store" })]); if (a.ok) { const rows = await a.json() as Calculation[]; setCalculations(rows); if (!calculationId && rows[0]) setCalculationId(String(rows[0].id)); } if (b.ok) setProposals(await b.json()); }, [calculationId, clientId]);
  useEffect(() => {
    // The state updates occur after the two network requests resolve.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load();
  }, [load]);
  async function createProposal() { setSaving(true); setMessage(""); const response = await fetch(`/api/clients/${clientId}/proposals`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ calculationId: Number(calculationId), validDays: 14, executionTerm: "Срок выполнения уточняется после замера", paymentTerms: "Порядок оплаты согласовывается при оформлении заказа", warranty: "Гарантия согласно договору", managerContact: "+7 708 575 0881" }) }); const body = await response.json(); setMessage(response.ok ? "КП подготовлено" : body.error ?? "Не удалось сформировать КП"); if (response.ok) await load(); setSaving(false); }
  async function setStatus(id: number, status: string) { const response = await fetch(`/api/proposals/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); if (!response.ok) return setMessage((await response.json()).error ?? "Не удалось изменить статус"); await load(); }
  async function convert(id: number) { if (!window.confirm("Клиент подтвердил заказ? Будет создан полноценный заказ.")) return; const response = await fetch(`/api/proposals/${id}/convert`, { method: "POST" }); const body = await response.json(); if (!response.ok) return setMessage(body.error ?? "Не удалось оформить заказ"); router.push(`/orders/${body.id}`); }
  const latest = proposals[0];
  return <main className="space-y-6 p-4 md:p-8"><header className="flex flex-wrap items-center justify-between gap-3"><div><Link href={`/clients/${clientId}`} className="text-blue-300">← К заявке</Link><h1 className="mt-2 text-3xl font-bold text-white">Расчёт и коммерческое предложение</h1><p className="text-slate-400">Один экран: расчёт, ручная продажная цена, КП и оформление заказа.</p></div></header>
    {message && <p role="status" className="rounded-xl border border-slate-700 p-4 text-slate-200">{message}</p>}
    <section className="rounded-2xl border border-slate-700 bg-[#101827] p-4 md:p-7"><StairCalculator clientId={clientId}/></section>
    <PriceObjectionPanel clientId={clientId} calculations={calculations} proposalId={proposals[0]?.id} onDone={setMessage}/>
    <section className="rounded-2xl border border-slate-700 bg-[#101827] p-5"><h2 className="text-xl font-semibold text-white">Сформировать КП из сохранённого расчёта</h2><div className="mt-4 flex flex-col gap-3 sm:flex-row"><select value={calculationId} onChange={(event)=>setCalculationId(event.target.value)} className="min-h-11 flex-1 rounded-xl bg-slate-900 px-3 text-white"><option value="">Выберите расчёт</option>{calculations.map((item)=><option key={item.id} value={item.id}>{new Date(item.createdAt).toLocaleString("ru-RU")} · {item.material} · {money(item.clientPrice)}</option>)}</select><button disabled={saving || !calculationId} onClick={()=>void createProposal()} className="min-h-11 rounded-xl bg-blue-600 px-5 font-semibold text-white disabled:opacity-50">Сформировать КП</button></div></section>
    {latest && <section className="print:bg-white print:text-black rounded-2xl border border-slate-700 bg-white p-6 text-slate-900 md:p-10"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold text-blue-700">{latest.snapshot.company?.name ?? "ALTYN SAPA COMPANY"}</p><h2 className="mt-2 text-2xl font-bold">Коммерческое предложение № {latest.number}</h2><p className="text-sm text-slate-500">Действительно до {new Date(latest.validUntil).toLocaleDateString("ru-RU")}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-sm">{latest.status}</span></div><div className="mt-7 grid gap-4 sm:grid-cols-2"><div><b>Клиент</b><p>{latest.snapshot.client?.name}</p><p>{latest.snapshot.client?.phone}</p><p>{latest.snapshot.client?.city}</p></div><div><b>Менеджер</b><p>{latest.snapshot.manager}</p><p>{latest.managerContact}</p></div></div><div className="mt-6 rounded-xl bg-slate-100 p-5"><p className="text-sm text-slate-600">Итоговая стоимость</p><p className="text-3xl font-bold">{money(latest.snapshot.clientPrice ?? 0)}</p></div><div className="mt-6 grid gap-3 text-sm"><p><b>Срок:</b> {latest.executionTerm}</p><p><b>Оплата:</b> {latest.paymentTerms}</p><p><b>Гарантия:</b> {latest.warranty}</p></div><div className="mt-7 flex flex-wrap gap-3 print:hidden"><button onClick={()=>window.print()} className="rounded-xl bg-slate-800 px-5 py-3 text-white">Печать / PDF</button>{latest.status !== "Отправлено" && <button onClick={()=>void setStatus(latest.id,"Отправлено")} className="rounded-xl bg-blue-600 px-5 py-3 text-white">КП отправлено</button>}{latest.status !== "Принято" && <button onClick={()=>void setStatus(latest.id,"Принято")} className="rounded-xl bg-green-700 px-5 py-3 text-white">КП принято</button>}{latest.status === "Принято" && !latest.conversion && <button onClick={()=>void convert(latest.id)} className="rounded-xl bg-emerald-600 px-5 py-3 font-semibold text-white">Оформить заказ</button>}{latest.conversion && <Link href={`/orders/${latest.conversion.orderId}`} className="rounded-xl bg-emerald-600 px-5 py-3 text-white">Открыть заказ</Link>}</div></section>}
  </main>;
}
