CREATE TYPE "PurchaseBatchStatus" AS ENUM ('DRAFT','ORDERED','IN_TRANSIT','RECEIVED_PROVISIONAL','COST_FINALIZED','CLOSED','CANCELLED');
CREATE TYPE "PurchaseAllocationMethod" AS ENUM ('BY_PURCHASE_VALUE','BY_QUANTITY','BY_WEIGHT','MANUAL');
CREATE TYPE "PurchaseCostType" AS ENUM ('SUPPLIER_COMMISSION','BANK_COMMISSION','CARGO','DELIVERY','CUSTOMS','INSURANCE','PACKAGING','CERTIFICATION','OTHER','SUPPLIER_CREDIT');
CREATE TYPE "InventoryCostStatus" AS ENUM ('LEGACY_UNVERIFIED','PROVISIONAL','FINAL');

ALTER TABLE "Material" ADD COLUMN "averageCost" DECIMAL(18,6) NOT NULL DEFAULT 0,
ADD COLUMN "inventoryValue" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN "valuationVersion" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN "costStatus" "InventoryCostStatus" NOT NULL DEFAULT 'LEGACY_UNVERIFIED';
ALTER TABLE "MaterialMovement" ADD COLUMN "unitCostSnapshot" DECIMAL(18,6),
ADD COLUMN "totalCogs" DECIMAL(18,2), ADD COLUMN "valuationMethod" TEXT,
ADD COLUMN "valuationVersion" INTEGER, ADD COLUMN "purchaseBatchLineId" INTEGER;

CREATE TABLE "Supplier" ("id" SERIAL PRIMARY KEY,"name" TEXT NOT NULL,"country" TEXT NOT NULL DEFAULT '',"defaultCurrency" TEXT NOT NULL DEFAULT 'KZT',"contact" TEXT NOT NULL DEFAULT '',"comment" TEXT NOT NULL DEFAULT '',"active" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "PurchaseBatch" ("id" SERIAL PRIMARY KEY,"number" TEXT NOT NULL,"supplierId" INTEGER NOT NULL,"orderDate" TIMESTAMP(3) NOT NULL,"expectedArrivalDate" TIMESTAMP(3),"actualArrivalDate" TIMESTAMP(3),"purchaseCurrency" TEXT NOT NULL DEFAULT 'KZT',"fixedExchangeRate" DECIMAL(18,6) NOT NULL DEFAULT 1,"allocationMethod" "PurchaseAllocationMethod" NOT NULL DEFAULT 'BY_PURCHASE_VALUE',"responsibleUserId" INTEGER NOT NULL,"notes" TEXT NOT NULL DEFAULT '',"status" "PurchaseBatchStatus" NOT NULL DEFAULT 'DRAFT',"purchaseGoodsCostKzt" DECIMAL(18,2) NOT NULL DEFAULT 0,"additionalCostKzt" DECIMAL(18,2) NOT NULL DEFAULT 0,"landedCostKzt" DECIMAL(18,2) NOT NULL DEFAULT 0,"finalizedAt" TIMESTAMP(3),"finalizedByUserId" INTEGER,"version" INTEGER NOT NULL DEFAULT 1,"idempotencyKey" TEXT,"requestHash" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "PurchaseBatchLine" ("id" SERIAL PRIMARY KEY,"batchId" INTEGER NOT NULL,"materialId" INTEGER NOT NULL,"orderedQuantity" DECIMAL(18,3) NOT NULL,"receivedQuantity" DECIMAL(18,3) NOT NULL DEFAULT 0,"rejectedQuantity" DECIMAL(18,3) NOT NULL DEFAULT 0,"returnedQuantity" DECIMAL(18,3) NOT NULL DEFAULT 0,"purchaseUnitPrice" DECIMAL(18,6) NOT NULL,"purchaseCurrency" TEXT NOT NULL,"exchangeRateSnapshot" DECIMAL(18,6) NOT NULL,"purchaseCostKzt" DECIMAL(18,2) NOT NULL DEFAULT 0,"weight" DECIMAL(18,3),"allocatedAdditionalCost" DECIMAL(18,2) NOT NULL DEFAULT 0,"provisionalUnitLandedCost" DECIMAL(18,6) NOT NULL DEFAULT 0,"finalUnitLandedCost" DECIMAL(18,6),"costStatus" "InventoryCostStatus" NOT NULL DEFAULT 'PROVISIONAL',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "PurchaseAdditionalCost" ("id" SERIAL PRIMARY KEY,"batchId" INTEGER NOT NULL,"type" "PurchaseCostType" NOT NULL,"provider" TEXT NOT NULL,"currency" TEXT NOT NULL,"foreignAmount" DECIMAL(18,2) NOT NULL,"exchangeRate" DECIMAL(18,6) NOT NULL,"amountKzt" DECIMAL(18,2) NOT NULL,"documentDate" TIMESTAMP(3) NOT NULL,"paymentDate" TIMESTAMP(3),"allocationMethod" "PurchaseAllocationMethod" NOT NULL,"comment" TEXT NOT NULL DEFAULT '',"reference" TEXT,"createdByUserId" INTEGER NOT NULL,"idempotencyKey" TEXT,"requestHash" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "PurchaseCostRevision" ("id" SERIAL PRIMARY KEY,"batchId" INTEGER NOT NULL,"previousLandedTotal" DECIMAL(18,2) NOT NULL,"addedCost" DECIMAL(18,2) NOT NULL,"newLandedTotal" DECIMAL(18,2) NOT NULL,"allocation" JSONB NOT NULL,"remainingInventoryDelta" DECIMAL(18,2) NOT NULL DEFAULT 0,"consumedCogsAdjustment" DECIMAL(18,2) NOT NULL DEFAULT 0,"authorId" INTEGER NOT NULL,"reason" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "InventoryValuationEntry" ("id" SERIAL PRIMARY KEY,"materialId" INTEGER NOT NULL,"quantity" DECIMAL(18,3) NOT NULL,"unitCost" DECIMAL(18,6) NOT NULL,"totalValue" DECIMAL(18,2) NOT NULL,"type" TEXT NOT NULL,"sourceType" TEXT NOT NULL,"sourceId" INTEGER,"version" INTEGER NOT NULL,"costStatus" "InventoryCostStatus" NOT NULL,"reason" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "InventoryCogsEntry" ("id" SERIAL PRIMARY KEY,"materialId" INTEGER NOT NULL,"movementId" INTEGER NOT NULL,"orderId" INTEGER,"quantity" DECIMAL(18,3) NOT NULL,"unitCostSnapshot" DECIMAL(18,6) NOT NULL,"totalCogs" DECIMAL(18,2) NOT NULL,"valuationMethod" TEXT NOT NULL DEFAULT 'MOVING_WEIGHTED_AVERAGE',"valuationVersion" INTEGER NOT NULL,"adjustmentOfId" INTEGER,"reason" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE UNIQUE INDEX "PurchaseBatch_number_key" ON "PurchaseBatch"("number"); CREATE UNIQUE INDEX "PurchaseBatch_idempotencyKey_key" ON "PurchaseBatch"("idempotencyKey");
CREATE UNIQUE INDEX "PurchaseBatchLine_batchId_materialId_key" ON "PurchaseBatchLine"("batchId","materialId"); CREATE UNIQUE INDEX "PurchaseAdditionalCost_idempotencyKey_key" ON "PurchaseAdditionalCost"("idempotencyKey"); CREATE UNIQUE INDEX "InventoryCogsEntry_movementId_key" ON "InventoryCogsEntry"("movementId");
CREATE INDEX "Supplier_active_name_idx" ON "Supplier"("active","name"); CREATE INDEX "PurchaseBatch_status_orderDate_idx" ON "PurchaseBatch"("status","orderDate"); CREATE INDEX "PurchaseBatch_supplierId_orderDate_idx" ON "PurchaseBatch"("supplierId","orderDate"); CREATE INDEX "PurchaseAdditionalCost_batchId_documentDate_idx" ON "PurchaseAdditionalCost"("batchId","documentDate"); CREATE INDEX "PurchaseCostRevision_batchId_createdAt_idx" ON "PurchaseCostRevision"("batchId","createdAt"); CREATE INDEX "InventoryValuationEntry_materialId_createdAt_idx" ON "InventoryValuationEntry"("materialId","createdAt"); CREATE INDEX "InventoryCogsEntry_orderId_createdAt_idx" ON "InventoryCogsEntry"("orderId","createdAt"); CREATE INDEX "InventoryCogsEntry_materialId_createdAt_idx" ON "InventoryCogsEntry"("materialId","createdAt");

ALTER TABLE "PurchaseBatch" ADD CONSTRAINT "PurchaseBatch_supplierId_fkey" FOREIGN KEY ("supplierId") REFERENCES "Supplier"("id") ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT "PurchaseBatch_responsibleUserId_fkey" FOREIGN KEY ("responsibleUserId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT "PurchaseBatch_finalizedByUserId_fkey" FOREIGN KEY ("finalizedByUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "PurchaseBatchLine" ADD CONSTRAINT "PurchaseBatchLine_batchId_fkey" FOREIGN KEY ("batchId") REFERENCES "PurchaseBatch"("id") ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT "PurchaseBatchLine_materialId_fkey" FOREIGN KEY ("materialId") REFERENCES "Material"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PurchaseAdditionalCost" ADD CONSTRAINT "PurchaseAdditionalCost_batchId_fkey" FOREIGN KEY ("batchId") REFERENCES "PurchaseBatch"("id") ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT "PurchaseAdditionalCost_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PurchaseCostRevision" ADD CONSTRAINT "PurchaseCostRevision_batchId_fkey" FOREIGN KEY ("batchId") REFERENCES "PurchaseBatch"("id") ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT "PurchaseCostRevision_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "InventoryValuationEntry" ADD CONSTRAINT "InventoryValuationEntry_materialId_fkey" FOREIGN KEY ("materialId") REFERENCES "Material"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "InventoryCogsEntry" ADD CONSTRAINT "InventoryCogsEntry_materialId_fkey" FOREIGN KEY ("materialId") REFERENCES "Material"("id") ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT "InventoryCogsEntry_movementId_fkey" FOREIGN KEY ("movementId") REFERENCES "MaterialMovement"("id") ON DELETE RESTRICT ON UPDATE CASCADE, ADD CONSTRAINT "InventoryCogsEntry_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE SET NULL ON UPDATE CASCADE, ADD CONSTRAINT "InventoryCogsEntry_adjustmentOfId_fkey" FOREIGN KEY ("adjustmentOfId") REFERENCES "InventoryCogsEntry"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "MaterialMovement" ADD CONSTRAINT "MaterialMovement_purchaseBatchLineId_fkey" FOREIGN KEY ("purchaseBatchLineId") REFERENCES "PurchaseBatchLine"("id") ON DELETE SET NULL ON UPDATE CASCADE;

UPDATE "Material" SET "averageCost"="purchasePrice", "inventoryValue"=ROUND(("stock"::numeric * "purchasePrice"),2), "costStatus"='LEGACY_UNVERIFIED';
INSERT INTO "InventoryValuationEntry" ("materialId","quantity","unitCost","totalValue","type","sourceType","version","costStatus","reason") SELECT "id","stock","purchasePrice",ROUND(("stock"::numeric * "purchasePrice"),2),'OPENING','LEGACY',1,'LEGACY_UNVERIFIED','Opening valuation from legacy purchasePrice; historical movements unchanged' FROM "Material" WHERE "stock" <> 0;
